### ISSUE TITLE
TypeError: Cannot compare tz-naive and tz-aware timestamps

### ISSUE THREAD

**Issue by evellynsc** [nilmtk/nilmtk#366] opened 2015-03-25 21:19 UTC
I am trying to use the disaggregate function with the combinatorial optimisation algorithm as shown in the code below, but it returns a type error. Any suggestion on how I can fix it?

```python
from nilmtk import DataSet, TimeFrame
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.disaggregate import FHMM

redd = DataSet('/home/evellyn/LaCCAN/NILM/data/redd/redd.h5')
redd.set_window(start=None, end='2011-05-01 00:00:00')
elec = redd.buildings[1].elec
co = CombinatorialOptimisation()
co.train(elec)
redd.store.window = TimeFrame(start='2011-05-01 00:00:00', end=None)
mains = elec.mains()
output = HDFDataStore('output.h5', 'w')
co.disaggregate(mains, output)
```

-----------
UPDATE

I've just tested something new and it worked!

Just changed
```python
redd.store.window = TimeFrame(start='2011-05-01 00:00:00', end=None)
```
for 
```python
redd.set_window(start='2011-05-01 00:00:00', end=None)
```
------------------

Terminal output:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-a2892f84e6bf> in <module>()
----> 1 co.disaggregate(mains, output)

/home/evellyn/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.pyc in disaggregate(self, mains, output_datastore, **load_kwargs)
    110 
    111         # Add vampire power to the model
--> 112         vampire_power = mains.vampire_power()
    113         print("vampire_power = {} watts".format(vampire_power))
    114         n_rows = state_combinations.shape[0]

/home/evellyn/nilmtk/nilmtk/electric.pyc in vampire_power(self, **load_kwargs)
    183     def vampire_power(self, **load_kwargs):
    184         # TODO: this might be a naive approach to calculating vampire power.
--> 185         return self.power_series_all_data(**load_kwargs).min()
    186 
    187     def uptime(self, **load_kwargs):

/home/evellyn/nilmtk/nilmtk/electric.pyc in power_series_all_data(self, **kwargs)
     81     def power_series_all_data(self, **kwargs):
     82         chunks = []
---> 83         for series in self.power_series(**kwargs):
     84             if len(series) > 0:
     85                 chunks.append(series)

/home/evellyn/nilmtk/nilmtk/electric.pyc in load_series(self, **kwargs)
    586         physical_quantity = kwargs['physical_quantity']
    587         generator = self.load(**kwargs)
--> 588         for chunk in generator:
    589             if chunk.empty:
    590                 yield chunk

/home/evellyn/nilmtk/nilmtk/metergroup.pyc in load(self, **kwargs)
    644         # Handle kwargs
    645         sample_period = kwargs.setdefault('sample_period', self.sample_period())
--> 646         sections = kwargs.pop('sections', [self.get_timeframe()])
    647         chunksize = kwargs.pop('chunksize', MAX_MEM_ALLOWANCE_IN_BYTES)
    648         duration_threshold = sample_period * chunksize

/home/evellyn/nilmtk/nilmtk/metergroup.pyc in get_timeframe(self)
   1332         for meter in self.meters:
   1333             if timeframe is None:
-> 1334                 timeframe = meter.get_timeframe()
   1335             elif meter.get_timeframe().empty:
   1336                 pass

/home/evellyn/nilmtk/nilmtk/elecmeter.pyc in get_timeframe(self)
     98     def get_timeframe(self):
     99         self._check_store()
--> 100         return self.store.get_timeframe(key=self.key)
    101 
    102     def _check_store(self):

/home/evellyn/nilmtk/nilmtk/docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__','__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/home/evellyn/nilmtk/nilmtk/datastore/hdfdatastore.pyc in get_timeframe(self, key)
    220         data_end_date = self.store.select(key, start=-1).index[0]
    221         timeframe = TimeFrame(data_start_date, data_end_date)
--> 222         return self.window.intersection(timeframe)
    223 
    224     def _check_columns(self, key, columns):

/home/evellyn/nilmtk/nilmtk/timeframe.pyc in intersection(self, other)
    151                 start = other.start
    152             else:
--> 153                 start = max(self.start, other.start)
    154 
    155             if other.end is None:

/home/evellyn/anaconda/lib/python2.7/site-packages/pandas/tslib.so in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:15492)()

/home/evellyn/anaconda/lib/python2.7/site-packages/pandas/tslib.so in pandas.tslib._Timestamp._assert_tzawareness_compat (pandas/tslib.c:15846)()

TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by nipunreddevil** [comment] 2015-03-25 21:36
Thanks for reporting this bug @evellynsc.

I ran your sample code and could reproduce this behaviour. However, the following line is not needed

`redd.store.window = TimeFrame(start='2011-05-01 00:00:00', end=None)`

I ran your code after removing this line and it works well. Please let us know if this works for you. 

Can you also please let us know what resource you referred for the above mentioned code? We might have forgotten to update documentation somewhere :)

**Comment by evellynsc** [comment] 2015-03-25 21:44
Thanks for your fast answer @nipunreddevil. I supposed that line was necessary to select the second half of dataset for testing.

The resource is on http://nilmtk.github.io/nilmtk/master/disaggregation_and_metrics.html, the second piece of code.

**Comment by nipunreddevil** [comment] 2015-03-25 22:03
It is a case of docs a bit of sync. 

Please refer the following `IPython` to see how to divide the data set into training and testing. It also contains some more things which you may find useful. 

I'll close this issue now and create a new one to mention that the [Disaggregation and metrics](http://nilmtk.github.io/nilmtk/master/disaggregation_and_metrics.html) docs need to be updated.

**Closed by nipunreddevil** 2015-03-25 22:03 UTC

**Comment by evellynsc** [comment] 2015-03-26 18:54
@nipunreddevil, thanks for your recommedation! Now, I ran the notebook and again I got the same type error. This time trying to select the top-5 appliances from this section [Selecting top-5 appliance] (http://nbviewer.ipython.org/github/nilmtk/nilmtk/blob/master/notebooks/experimental/co_fhmm.ipynb#Selecting-top-5-appliances).

```python 
top_5_train_elec = train_elec.submeters().select_top_k(k=5)
```
Output:

```python
1/16 ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-101-5438c0269107> in <module>()
----> 1 top_5_train_elec = train_elec.submeters().select_top_k(k=5)

/home/evellyn/nilmtk/nilmtk/metergroup.pyc in select_top_k(self, k, by, asc, group_remainder, **kwargs)
   1290         """
   1291         function_map = {'energy': self.fraction_per_meter, 'entropy': self.entropy_per_meter}
-> 1292         top_k_series = function_map[by](**kwargs)
   1293         top_k_series.sort(ascending=asc)
   1294         top_k_elec_meter_ids = top_k_series[:k].index

/home/evellyn/nilmtk/nilmtk/metergroup.pyc in fraction_per_meter(self, **load_kwargs)
   1169         Each value is a float in the range [0,1].
   1170         """
-> 1171         energy_per_meter = self.energy_per_meter(**load_kwargs).max()
   1172         total_energy = energy_per_meter.sum()
   1173         return energy_per_meter / total_energy

/home/evellyn/nilmtk/nilmtk/metergroup.pyc in energy_per_meter(self, per_period, mains, use_meter_labels, **load_kwargs)
   1117             stdout.flush()
   1118             if per_period is None:
-> 1119                 meter_energy = meter.total_energy(**load_kwargs)
   1120             else:
   1121                 load_kwargs.setdefault('use_uptime', False)

/home/evellyn/nilmtk/nilmtk/elecmeter.pyc in total_energy(self, **loader_kwargs)
    595         nodes = [Clip, TotalEnergy]
    596         return self._get_stat_from_cache_or_compute(
--> 597             nodes, TotalEnergy.results_class(), loader_kwargs)
    598 
    599     def dropout_rate(self, ignore_gaps=True, **loader_kwargs):

/home/evellyn/nilmtk/nilmtk/elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    688         if loader_kwargs.get('preprocessing') is None:
    689             cached_stat = self.get_cached_stat(key_for_cached_stat)
--> 690             results_obj.import_from_cache(cached_stat, sections)
    691 
    692             def find_sections_to_compute():

/home/evellyn/nilmtk/nilmtk/results.pyc in import_from_cache(self, cached_stat, sections)
    161             else:
    162                 if isinstance(rows_matching_start, pd.Series):
--> 163                     append_row(rows_matching_start, section)
    164                 else:
    165                     for row_i in range(rows_matching_start.shape[0]):

/home/evellyn/nilmtk/nilmtk/results.pyc in append_row(row, section)
    148             # so now we must put the timezone back.
    149             row['end'] = tz_localize_naive(row['end'], tz)
--> 150             if row['end'] == section.end:
    151                 usable_sections_from_cache.append(row)
    152 

/home/evellyn/anaconda/lib/python2.7/site-packages/pandas/tslib.so in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:15492)()

/home/evellyn/anaconda/lib/python2.7/site-packages/pandas/tslib.so in pandas.tslib._Timestamp._assert_tzawareness_compat (pandas/tslib.c:15816)()

TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by nipunreddevil** [comment] 2015-03-26 19:00
I think this error is caused due to `caching`. I think some entries were cached when you used older code. 
Can you try running `we.clear_cache()` after you've written `we = DataSet(join(data_dir, 'redd.h5'))` . I think you should be able to proceed further after doing this.

**Comment by evellynsc** [comment] 2015-03-26 21:27
Thanks a lot, @nipunreddevil! This worked for me!

**Comment by JackKelly** [comment] 2015-03-26 21:40
great work @nipunreddevil ;)

**Comment by nipunreddevil** [comment] 2015-03-26 23:31
Thanks @JackKelly :)
