### ISSUE TITLE
Request for validation of disaggregation results

### ISSUE THREAD

**Issue by akshay-sn** [nilmtk/nilmtk#394] opened 2015-05-21 15:55 UTC
Hello,

We are trying to disaggregate iAWE dataset using CO. 
We obtain a FTE (fraction_energy_assigned_correctly) of 0.451 

Training Period:  start_date '2013-05-24 00:00:00' and end_date= 2013-08-21 00:00:00'
Disaggregation time period:  start_date=14-07-2013 00:00:00 and end_date=27/7/2013 00:00:00. 

The question is 
a) is there a simple way to validate this number?
b) The NILMTK paper says the FTE is around 0.89, hence can you verify the above obtained number in your nilmtk environment. 
c) Could you run the disaggregation for CO using iAWE for the specified dates, so that it is clear the results are consistent.

**Comment by nipunreddevil** [comment] 2015-05-23 09:55
Hi Akshay,

The results reported in the paper are from version 0.1 of nilmtk. Since then, a lot of things have changed.

The evaluation done in that paper was as follows:

1. First half of each data set was used for training
2. Second half for disaggregation
3. Top-k appliances were chosen

More details can be found here:
1. https://github.com/nilmtk/nilmtk/blob/v0.1.0/notebooks/disaggregation_across_datasets.ipynb
2. https://github.com/nilmtk/nilmtk/blob/v0.1.0/notebooks/disaggregation_single_dataset_detailed.ipynb


As far as validating your numbers is concerned, I would expect them to be same when I run them as well. I think we've fixed random seeds to ensure repeatability. I'll try and run your code whenever possible.

Do multiple of your runs give you the same number?

**Comment by akshay-sn** [comment] 2015-05-26 16:03
Hi Nipun,

Yes multiple runs give me the same number :) Do let me know when you get time to check it out.

Also, another question when I looked into the appliance level data (3.csv,4.csv, etc.) and compare with mains, there are two issues

i) Each appliance starting time period is different for example, fridge starts from 7th June and Washing machine starts from 10th June, whereas mains have data from 22nd May.

ii) Also, When compared to original iAWE dataset on your blog, the data used for NILMTK has some missing data.

iii) The difference between the Sum of appliances and Mains is very huge (on an average >350W) and you still use vampire power =0. Which is very strange?

These questions helps us to use the dataset in a correct manner. Thanks in advance.
Akshay

**Comment by nipunreddevil** [comment] 2015-06-10 11:48
Hi Akshay,
Apologies for the delayed response. Have had a tight schedule. I am working on a FAQ for my data set and will try to answer all your questions by tomorrow.

**Comment by nipunreddevil** [comment] 2015-06-10 12:26
Akshay, 
For some reason, I am not able to get metrics working properly on my code. I've opened a new issue in this regards: https://github.com/nilmtk/nilmtk/issues/406

**Comment by nipunreddevil** [comment] 2015-06-11 09:59
Akshay,
I've created a FAQ for the data set and have answered all your questions.
Link to the data set page: http://iawe.github.io

Let me know if we can close this issue.

**Comment by akshay-sn** [comment] 2015-06-11 10:12
Hi Nipun,

Thanks for the replies. It does answer our questions. The reason for those questions were

a) When we disaggregate with variation in baseline (vampire power) the disaggregation result will be bad due to the mismatch when you use CO.

b) Can you provide the HDF5 file which you mention in FAQ question3. So that we can use the cleaned data.

Cheers,
Akshay

**Comment by nipunreddevil** [comment] 2015-06-11 10:31
>Can you provide the HDF5 file which you mention in FAQ question3. So that we can use the cleaned data.

Link: https://www.copy.com/s/t%3AiMrM8OYrqklWOW40%3Bp%3A%252Fiawe_cleaned.h5

I'll put it up on the data set page also soon. This contains 22 days of data. I hope to add an IPython notebook showing how to use it within nilmtk and also to benchmark NILM algorithms. That might take some time.


>When we disaggregate with variation in baseline (vampire power) the disaggregation result will be bad due to the mismatch when you use CO.

I think you are right. I think a caveat is how vampire power should be defined. Should it be the minimum aggregate power? This definition can give a vampire power of zero when, say 99% of the times the baseline is 100W (due to some unaccounted appliance which is always on), and 1% of the times, the baseline is 0W. Should, the vampire power be 0W or 100W.

@JackKelly : What do you think is an appropriate definition?

**Comment by akshay-sn** [comment] 2015-06-11 10:36
@nipunreddevil Thanks for the h5 file. 

@nipunreddevil @JackKelly I think the key to accurate disaggregation of energy lies in using the right vampire power. Here in TUDelft, we are trying different ways to ensure this is accounted as accurately as possible. Such that, during disaggregation CO can indeed consider right set of appliances. Any suggestions from you guys would be also very useful.

**Comment by JackKelly** [comment] 2015-06-11 11:53
@akshay-sn @nipunreddevil very interesting discussion!  I don't have a perfect definition of vampire power.  I think that the precise definition will vary a bit depending on exactly what your end-goal is and what the time duration of the input is.  For example, if we define vampire power as just the minimum power demand then it will *always* be zero if we consider a wide enough time window (e.g. a time window which includes the construction or demolition of the house, or a power cut, or a period of major building work etc).

>  I think the key to accurate disaggregation of energy lies in using the right vampire power.

I think that's very likely to be true if we use CO or FHMM.  And this is part of the reason why I suspect there are better algorithms for NILM :)

**Comment by akshay-sn** [comment] 2015-06-11 12:31
@JackKelly @nipunreddevil Thanks for the discussion. We are currently trying couple of techniques to derive vampire power towards energy disaggregation. We could have an offline discussion if you have some thoughts. 

Akshay
http://www.st.ewi.tudelft.nl/~akshay/
akshay.uttama@gmail.com

**Comment by nipunreddevil** [comment] 2015-06-16 09:19
@akshay-sn : Another way to look at the discussion on vampire power is to use event based methods. 

We have an implementation of Hart's 1985 NILM algorithm (although it isn't tested as thoroughly as I would have liked). Some notes on it are mentioned below:

1. http://nipunbatra.github.io/2014/11/hart-nilmtk/
2. http://nipunbatra.github.io/2014/08/hart,%20nilm,%20nilmtk/
3. https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/hart_85.py

**Comment by gjwo** [comment] 2015-06-17 08:29
@nipunreddevil I am trying out your notebook, but I am having problems installing seaborn on windows, how critical is this? can I remove seaborn calls as cosmetic only?

**Comment by oliparson** [comment] 2015-06-17 08:32
I'm pretty sure seaborn is cosmetic only.

**Comment by gjwo** [comment] 2015-06-17 08:33
Thanks

**Comment by gjwo** [comment] 2015-06-17 08:41
Ok next problem
```python
In [1]:

from nilmtk.utils import dependencies_diagnostics
pd.DataFrame(pd.Series(dependencies_diagnostics(), name="Value"))
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9d8b90d34ba6> in <module>()
----> 1 from nilmtk.utils import dependencies_diagnostics
      2 pd.DataFrame(pd.Series(dependencies_diagnostics(), name="Value"))

ImportError: cannot import name dependencies_diagnostics
```

**Comment by nipunreddevil** [comment] 2015-06-17 09:05
>ImportError: cannot import name dependencies_diagnostics

You are right! We renamed this method at some point of time. I forgot to change the notebook. And, seaborn is cosmetic.

**Comment by gjwo** [comment] 2015-06-17 09:18
Now an issue with the column types - mine are apparent and reactive. I was never very clear what the difference is between active and apparent, not what a CT clamp measures 
```python

Let us perform our analysis on selected 2 days
In [15]:

gjw.store.window = TimeFrame(start='2013-12-03 00:00:00', end='2013-12-04 00:00:00')
elec = gjw.buildings[building_number].elec
mains = elec.mains()
Training
We'll now do the training from the aggregate data. The algorithm segments the time series data into steady and transient states. Thus, we'll first figure out the transient and the steady states. Next, we'll try and pair the on and the off transitions based on their proximity in time and value.
In [12]:

from nilmtk.disaggregate.hart_85 import Hart85
h = Hart85()
h.train(mains)
​
---------------------------------------------------------------------------
MeasurementError                          Traceback (most recent call last)
<ipython-input-12-18a6d29df5d7> in <module>()
      1 from nilmtk.disaggregate.hart_85 import Hart85
      2 h = Hart85()
----> 3 h.train(mains)
      4 mains.head()

c:\users\gjwood\nilmtk\nilmtk\disaggregate\hart_85.pyc in train(self, metergroup, cols, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    231         self.state_threshold = state_threshold
    232         self.noise_level = noise_level
--> 233         [self.steady_states, self.transients] = find_steady_states_transients(metergroup,  cols, noise_level, state_threshold, **kwargs)
    234         self.pair_df = self.pair(buffer_size, min_tolerance, percent_tolerance, large_transition)
    235         self.centroids = hart85_means_shift_cluster(self.pair_df, cols)

c:\users\gjwood\nilmtk\nilmtk\feature_detectors\steady_states.pyc in find_steady_states_transients(metergroup, cols, noise_level, state_threshold, **load_kwargs)
     14     transients_list = []
     15 
---> 16     for power_df in metergroup.load(cols=cols, **load_kwargs):
     17         """
     18         if len(power_df.columns) <= 2:

c:\users\gjwood\nilmtk\nilmtk\elecmeter.pyc in load(self, **kwargs)
    447         # Get source node
    448         preprocessing = kwargs.pop('preprocessing', [])
--> 449         last_node = self.get_source_node(**kwargs)
    450         generator = last_node.generator
    451 

c:\users\gjwood\nilmtk\nilmtk\elecmeter.pyc in get_source_node(self, **loader_kwargs)
    572                 "Cannot get source node if meter.store is None!")
    573 
--> 574         loader_kwargs = self._convert_physical_quantity_and_ac_type_to_cols(**loader_kwargs)
    575         generator = self.store.load(key=self.key, **loader_kwargs)
    576         self.metadata['device'] = self.device

c:\users\gjwood\nilmtk\nilmtk\elecmeter.pyc in _convert_physical_quantity_and_ac_type_to_cols(self, physical_quantity, ac_type, cols, **kwargs)
    526                     msg = ("'{}' is not a subset of the available columns: '{}'"
    527                            .format(cols, self.available_columns()))
--> 528                     raise MeasurementError(msg)
    529 
    530         msg = ""

MeasurementError: '[('power', 'active')]' is not a subset of the available columns: '[('power', 'apparent'), ('power', 'reactive')]'
```

**Comment by JackKelly** [comment] 2015-06-17 09:42
CT clamps without a voltage sensor give you an approximation of apparent
power.

Active power is also called real power.

**Comment by gjwo** [comment] 2015-06-17 10:15
OK got around that one, here's the next
```python

Training
We'll now do the training from the aggregate data. The algorithm segments the time series data into steady and transient states. Thus, we'll first figure out the transient and the steady states. Next, we'll try and pair the on and the off transitions based on their proximity in time and value.
In [48]:

from nilmtk.disaggregate.hart_85 import Hart85
h = Hart85()
h.train(mains,cols=[('power','apparent'),('power','reactive')])
​
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-e070a6ace91e> in <module>()
      1 from nilmtk.disaggregate.hart_85 import Hart85
      2 h = Hart85()
----> 3 h.train(mains,cols=[('power','apparent'),('power','reactive')])

c:\users\gjwood\nilmtk\nilmtk\disaggregate\hart_85.pyc in train(self, metergroup, cols, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    233         [self.steady_states, self.transients] = find_steady_states_transients(metergroup,  cols, noise_level, state_threshold, **kwargs)
    234         self.pair_df = self.pair(buffer_size, min_tolerance, percent_tolerance, large_transition)
--> 235         self.centroids = hart85_means_shift_cluster(self.pair_df, cols)
    236 
    237     def pair(self, buffer_size, min_tolerance, percent_tolerance, large_transition):

c:\users\gjwood\nilmtk\nilmtk\feature_detectors\cluster.pyc in hart85_means_shift_cluster(pair_buffer_df, cols)
    135                                                                      ((np.fabs(row['T1 Reactive']) + np.fabs(row['T2 Reactive'])) / 2), axis=1), index=pair_buffer_df.index)
    136 
--> 137     X = cluster_df.values.reshape((len(cluster_df.index), len(cols)))
    138     ms = MeanShift(bin_seeding=True)
    139     ms.fit(X)

ValueError: total size of new array must be unchanged
```

**Comment by gjwo** [comment] 2015-06-17 12:34
I also tried with apparent power alone as indicated in the code comments,  and got  a different error
```python
In [49]:

from nilmtk.disaggregate.hart_85 import Hart85
h = Hart85()
h.train(mains,cols=[('power','apparent')])
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-0fd1cf0ce185> in <module>()
      1 from nilmtk.disaggregate.hart_85 import Hart85
      2 h = Hart85()
----> 3 h.train(mains,cols=[('power','apparent')])

c:\users\gjwood\nilmtk\nilmtk\disaggregate\hart_85.pyc in train(self, metergroup, cols, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    233         [self.steady_states, self.transients] = find_steady_states_transients(metergroup,  cols, noise_level, state_threshold, **kwargs)
    234         self.pair_df = self.pair(buffer_size, min_tolerance, percent_tolerance, large_transition)
--> 235         self.centroids = hart85_means_shift_cluster(self.pair_df, cols)
    236 
    237     def pair(self, buffer_size, min_tolerance, percent_tolerance, large_transition):

c:\users\gjwood\nilmtk\nilmtk\feature_detectors\cluster.pyc in hart85_means_shift_cluster(pair_buffer_df, cols)
    137     X = cluster_df.values.reshape((len(cluster_df.index), len(cols)))
    138     ms = MeanShift(bin_seeding=True)
--> 139     ms.fit(X)
    140     labels = ms.labels_
    141     cluster_centers = ms.cluster_centers_

c:\Users\GJWood\Anaconda\lib\site-packages\sklearn\cluster\mean_shift_.pyc in fit(self, X, y)
    343             Samples to cluster.
    344         """
--> 345         X = check_array(X)
    346         self.cluster_centers_, self.labels_ = \
    347             mean_shift(X, bandwidth=self.bandwidth, seeds=self.seeds,

c:\Users\GJWood\Anaconda\lib\site-packages\sklearn\utils\validation.pyc in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features)
    358             raise ValueError("Found array with %d sample(s) (shape=%s) while a"
    359                              " minimum of %d is required."
--> 360                              % (n_samples, shape_repr, ensure_min_samples))
    361 
    362     if ensure_min_features > 0 and array.ndim == 2:

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
```

**Comment by nipunreddevil** [comment] 2015-06-17 15:01
Graham,
Can you please create a new issue for harts algorithm and put the full code
to reproduce the bug.

**Comment by gjwo** [comment] 2015-06-17 15:22
done, here https://github.com/nilmtk/nilmtk/issues/411

**Comment by akshay-sn** [comment] 2015-06-18 09:50
@nipunreddevil We are trying now to play around with smart*. I could not find any documentation on nilmtk with smart*. Please let me know if you have any notebooks to load and see the disaggregation results using SMART*.

**Comment by nipunreddevil** [comment] 2015-06-18 10:43
I talked to the Smart* authors a few days back and asked them if they could contribute a convertor. I haven't heard back yet.

In v0.1, I had written a converter for smart*. Refer 1 and 2
1. https://github.com/nilmtk/nilmtk/blob/v0.1.0/nilmtk/dataset/smart.py
2. https://github.com/nilmtk/nilmtk/blob/v0.1.0/nilmtk/dataset/smart_circuits.py

v0.1 notebook containing results from smart*: https://github.com/nilmtk/nilmtk/blob/v0.1.0/notebooks/disaggregation_across_datasets.ipynb

For v0.2, we decided that data set owners should write the convertors for their data sets. Thus, we haven't written a convertor for smart* for v0.2. It shouldn't take long, especially since v0.1 convertor code already exists.

**Comment by akshay-sn** [comment] 2015-06-18 11:11
Thanks a lot. I was mainly looking for the appliance_name_map how you renamed their circuits. That answers it :) 

One additional question, for your paper, did you do any preprocessing on smart* data? like how you removed water motar in iAWE. Because we are getting a very varied result in smart* as we were getting for iAWE also untill we removed water motar.

**Comment by nipunreddevil** [comment] 2015-06-18 11:35
Akshay,
The preprocessing we had done is present in the notebook I linked above. Copying here again:

```python

def preprocess_smart(building):
    building = prepb.filter_out_implausible_values(building, Measurement('power','active'), max_threshold=20000)
    #building = prepb.filter_channels_with_less_than_x_samples(building, 100)
    building  = prepb.filter_datetime(building, start_datetime='2012-04-30 06:00', end_datetime='2012-07-30')
    building = prepb.downsample(building)
    building = prepb.fill_appliance_gaps(building)
    #for appliance_name, appliance_df in building.utility.electric.appliances.iteritems():
    #    appliance_df.fillna(method='ffill',inplace=True, limit=2)
    
    building = prepb.prepend_append_zeros(building, '2012-04-30', '2012-07-30', '1T', 'US/Eastern')
    building = prepb.drop_missing_mains(building)
    building = prepb.make_common_index(building)
    building  = prepb.filter_contribution_less_than_x(building)
    building.utility.electric.appliances.pop(('heat pump',2))
    #for appliance_name, appliance_df in building.utility.electric.appliances.iteritems():
    #    appliance_df.fillna(0, inplace=True)
    return building
```

**Closed** 2016-01-09 12:43 UTC
