### ISSUE TITLE
On Windows 7 for Chinese language, python v3.6.3, nilmtk UnicodeDecodeError

### ISSUE THREAD

**Issue by dreamhavei** [nilmtk/nilmtk#686] opened 2018-07-10 11:09 UTC
Trying to run  `conda-env create -f path/environment.yaml` ,Igot
```
Exception:
Traceback (most recent call last):
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\compat\__ini
t__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 19: invalid
 start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\basecommand.
py", line 215, in main
    status = self.run(options, args)
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\commands\ins
tall.py", line 342, in run
    prefix=options.prefix_path,
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\req\req_set.
py", line 784, in install
    **kwargs
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\req\req_inst
all.py", line 878, in install
    spinner=spinner,
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\utils\__init
__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "B:\software\Anaconda3\envs\nilmtk-env\lib\site-packages\pip\compat\__ini
t__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 19: invalid
 start byte
```

**Comment by dreamhavei** [comment] 2018-07-10 11:30
Can we refer this []( https://github.com/decalage2/olefile/issues/80)  to modify

**Comment by PMeira** [comment] 2018-07-10 17:38
Looks like it's only related to pip. I can try to install the Chinese language pack to better test in a few days (probably tomorrow).

Meanwhile, can you check if installing via our experimental conda channel works for you? Just activate the target environment and run:
```
conda install -c pmeira nilmtk
```
It would be better to `pip uninstall` the packages from the channel (`nilmtk`, `nilm_metadata`, `hmmlearn`) if you previously installed them via pip.

**Comment by PMeira** [comment] 2018-07-11 21:03
@dreamhavei I couldn't get a Windows 7 installation to test, so I tried with Windows 10. 

- Installed MSVC 2015 build tools
- Installed the Chinese language pack, removed other languages, rebooted. 
- Finally, installed Miniconda and proceed to test the installation.

So far, no issues at all using our `environment.yml`. Using `conda install -c pmeira nilmtk` on a new/empty environment also worked fine.

The only thing I can imagine is that Windows 7 doesn't work the same as Windows 10 in this aspect. 
I even tried explicitly changing the codepage on the command prompt and it still worked.

I only have one more suggestion, setting the codepage to UTF-8 before running the command:

```
chcp 65001
conda-env create -f path/environment.yaml
```

I've seen some reports of similar errors and some people reported that this fixed it.

**Comment by PMeira** [comment] 2018-07-11 21:10
See also https://github.com/pypa/pip/issues/4251

**Comment by PMeira** [comment] 2018-08-13 02:36
Closing this since there were no updates and the issue is not in NILMTK itself.

**Closed by PMeira** 2018-08-13 02:36 UTC
