### ISSUE TITLE
Error at disaggregation with ECO using benchmarks algorithms [ValuError/IndexError]

### ISSUE THREAD

**Issue by nicolascassia** [nilmtk/nilmtk#709] opened 2018-10-26 20:12 UTC
Hi, I'm trying the example of comparing nilm algorithms in order to test the ECO dataset, but I'm getting a ValueError/IndexError, which occurs after the training.

Code: 

  ```python
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from six import iteritems
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

rcParams['figure.figsize'] = (13, 6)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation,FHMM

train = DataSet('/home/bteam/nilmtk/data/eco/eco.h5')
test = DataSet('/home/bteam/nilmtk/data/eco/eco.h5')

building = 2

train.set_window(end="1-10-2012")
test.set_window(start="1-10-2011")


train_elec = train.buildings[2].elec
test_elec = test.buildings[2].elec

top_5_train_elec = train_elec.submeters().select_top_k(k=5)

#Training and Disagregation
def predict(clf, test_elec, sample_period, timezone):
    pred = {}
    gt= {}

    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
        chunk_drop_na = chunk.dropna()
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i]={}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)    
            gt[i][meter] = next(meter.load(sample_period=sample_period))
        gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()
        
    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]
    
    #Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)
    
    
    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.ix[common_index_local]
    pred_overall = pred_overall.ix[common_index_local]
    appliance_labels = [m.label() for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall

classifiers = {'CO':CombinatorialOptimisation(), 'FHMM':FHMM()}
predictions = {}
sample_period = 120
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    clf.train(top_5_train_elec, sample_period=sample_period)
    gt, predictions[clf_name] = predict(clf, test_elec, 120, train.metadata['timezone'])
  ```

Output:
  ```python
********************
CO
********************
Training model for submeter 'ElecMeter(instance=4, building=2, dataset='ECO', appliances=[Appliance(type='tablet computer charger', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=2, dataset='ECO', appliances=[Appliance(type='air handling unit', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=2, dataset='ECO', appliances=[Appliance(type='dish washer', instance=1)])'
Done training!
Loading data for meter ElecMeterID(instance=3, building=2, dataset='ECO')     
Done loading data all meters for this chunk.
Estimating power demand for 'ElecMeter(instance=4, building=2, dataset='ECO', appliances=[Appliance(type='tablet computer charger', instance=1)])'

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-d877ad3dd5c0> in <module>
      7     print("*" *20)
      8     clf.train(top_3_train_elec, sample_period=sample_period)
----> 9     gt, predictions[clf_name] = predict(clf, test_elec, 120, train.metadata['timezone'])

<ipython-input-13-903d7942abdd> in predict(clf, test_elec, sample_period, timezone)
      6     for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
      7         chunk_drop_na = chunk.dropna()
----> 8         pred[i] = clf.disaggregate_chunk(chunk_drop_na)
      9         gt[i]={}
     10 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/combinatorial_optimisation.py in disaggregate_chunk(self, mains)
    249             predicted_power = state_combinations[
    250                 indices_of_state_combinations, i].flatten()
--> 251             column = pd.Series(predicted_power, index=mains.index, name=i)
    252             appliance_powers_dict[self.model[i]['training_metadata']] = column
    253         appliance_powers = pd.DataFrame(appliance_powers_dict, dtype='float32')

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    260                             'Length of passed values is {val}, '
    261                             'index implies {ind}'
--> 262                             .format(val=len(data), ind=len(index)))
    263                 except TypeError:
    264                     pass

ValueError: Length of passed values is 882000, index implies 176400
  ```

If I change the order of the algorithms I get an IndexError.
  ```python
********************
FHMM
********************
Submeter 'ElecMeter(instance=5, building=2, dataset='ECO', appliances=[Appliance(type='dish washer', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=8, building=2, dataset='ECO', appliances=[Appliance(type='HTPC', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=7, building=2, dataset='ECO', appliances=[Appliance(type='fridge', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=4, building=2, dataset='ECO', appliances=[Appliance(type='tablet computer charger', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=6, building=2, dataset='ECO', appliances=[Appliance(type='air handling unit', instance=1)])' has no samples, skipping...

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-af74080e9c63> in <module>
      6     print(clf_name)
      7     print("*" *20)
----> 8     clf.train(top_5_train_elec, sample_period=sample_period)
      9     gt, predictions[clf_name] = predict(clf, test_elec, 120, train.metadata['timezone'])

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in train(self, metergroup, num_states_dict, **load_kwargs)
    321             self.meters.append(meter)
    322 
--> 323         learnt_model_combined = create_combined_hmm(new_learnt_models)
    324         self.individual = new_learnt_models
    325         self.model = learnt_model_combined

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in create_combined_hmm(model)
    123                   for appliance in model]
    124 
--> 125     pi_combined = compute_pi_fhmm(list_pi)
    126     A_combined = compute_A_fhmm(list_A)
    127     [mean_combined, cov_combined] = compute_means_fhmm(list_means)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in compute_pi_fhmm(list_pi)
    111     result : Combined Pi for the FHMM
    112     """
--> 113     result = list_pi[0]
    114     for i in range(len(list_pi) - 1):
    115         result = np.kron(result, list_pi[i + 1])

IndexError: list index out of range
  ```

Show versions
 ```python
from nilmtk.utils import show_versions
show_versions()
  ```

Output:
 ```python

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-138-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 40.4.3
Cython: 0.29
numpy: 1.15.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

Date: 2018-10-26 17:03:46.567075
Platform: Linux-4.4.0-138-generic-x86_64-with-debian-jessie-sid
System version: 3.6
nilmtk version: 0.2.1
nilm_metadata version: 0.2.2
numpy version: 1.15.2
matplotlib version: 3.0.0
pandas version: 0.23.4
sklearn version: 0.19.2
hmmlearn version: 0.2.1
 
```

Thanks in advance!

**Comment by nicolascassia** [comment] 2018-12-06 02:54
Reading some old issues I figure out that I was missing some paramters, now I'm able to run CO successfully. However, I can't get FHMM to work. 

Any idea?

**Comment by salmanshahid8** [comment] 2018-12-14 12:17
@nicolascassia Facing the same issue in FHMM for REFIT. Did you solve it?

**Comment by nicolascassia** [comment] 2018-12-14 18:48
@salmanshahid8  Not yet. In the case of CO, it works fine if I specify that only active power has to be taken into account.

**Comment by nipunbatra** [comment] 2019-05-22 07:30
Assigned to @ayushp20

**Comment by ayushp20** [comment] 2019-05-24 13:36
Your train and test windows seem to be erroneous, i plotted the dataset and it starts from June 2012, so i modified the code accordingly.
The issue is that if you explore the submeter dataframes, a lot of the appliances don't have power readings other than active. So the following line needs to be modified to include only the part of the dataframe with active power. For this case:
```python
for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period)):
```
and
```python
gt[i][meter] = next(meter.load(physical_quantity = 'power',ac_type = 'active', sample_period=sample_period))
```
I've made the respective pull requests.
Check out the rest of the code for reference.
```python
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from six import iteritems
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

rcParams['figure.figsize'] = (13, 6)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation,FHMM

train = DataSet('/home/ayush/data/eco.h5')
test = DataSet('/home/ayush/data/eco.h5')
building = 2

train.set_window(end="08-01-2012")
test.set_window(start="08-01-2012", end = "09-01-2012")


train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

top_5_train_elec = train_elec.submeters().select_top_k(k=5)

start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=120)
end = time.time()
print("Runtime =", end-start, "seconds.")

def predict(clf, test_elec, sample_period, timezone):
  pred = {}
  gt= {}

  for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period)):
      chunk_drop_na = chunk.dropna()
      pred[i] = clf.disaggregate_chunk(chunk_drop_na)
      gt[i]={}

      for meter in test_elec.submeters().meters:
          # Only use the meters that we trained on (this saves time!)    
          gt[i][meter] = next(meter.load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period))
      gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i]) if len(v)}, index=next(iter(gt[i].values())).index).dropna()
      
  # If everything can fit in memory
  gt_overall = pd.concat(gt)
  gt_overall.index = gt_overall.index.droplevel()
  pred_overall = pd.concat(pred)
  pred_overall.index = pred_overall.index.droplevel()

  # Having the same order of columns
  gt_overall = gt_overall[pred_overall.columns]
  
  #Intersection of index
  gt_index_utc = gt_overall.index.tz_convert("UTC")
  pred_index_utc = pred_overall.index.tz_convert("UTC")
  common_index_utc = gt_index_utc.intersection(pred_index_utc)
  
  
  common_index_local = common_index_utc.tz_convert(timezone)
  gt_overall = gt_overall.ix[common_index_local]
  pred_overall = pred_overall.ix[common_index_local]
  appliance_labels = [m.label() for m in gt_overall.columns.values]
  gt_overall.columns = appliance_labels
  pred_overall.columns = appliance_labels
  return gt_overall, pred_overall

classifiers = {'FHMM':FHMM(), 'CO':CombinatorialOptimisation()}
predictions = {}
sample_period = 120
for clf_name, clf in classifiers.items():
  print("*"*20)
  print(clf_name)
  print("*" *20)
  clf.train(top_5_train_elec, sample_period=sample_period)
  gt, predictions[clf_name] = predict(clf, test_elec, 120, train.metadata['timezone'])
```

**Closed** 2019-05-24 14:52 UTC
