### ISSUE TITLE
Issue in New Installation Procedure 

### ISSUE THREAD

**Issue by RehanLiaqat** [nilmtk/nilmtk#747] opened 2019-05-22 03:31 UTC
Thanks for Developing and Sharing the NILM Package.

I have just completed the installation after making the effort for a week with old  procedure given and fulfilling the dependencies given in environment.yml file. It was very hard to complete the procedure as I am new user and not from CS background.

Now I saw the new installation procedure given few hours ago not giving any details . I tested it as it looks very simple but found the following errors

Here are the issues I found in new installation procedure.
I have Anaconda installed and used the following commands to create a new environment named nilmtk-env1. I am intentionally using "1" with name as I already installed nilmtk-env with old  procedure given and fulfilling the dependencies given in environment.yml file. The sequence of commands I wrote in Anaconda Prompt with Windows operating system are given below ans the error messages I found are also copied.Kindly guide us to resolve the issue., as for new users it is very hard to meet the dependencies.

Regards
Rehan Liaqat

(base) C:\Users\rehan>conda create --name nilmtk-env1
Collecting package metadata: done
Solving environment: done
## Package Plan ##
  environment location: C:\Users\rehan\Anaconda3\envs\nilmtk-env1
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.

(base) C:\Users\rehan>pip install setuptools
Requirement already satisfied: setuptools in c:\users\rehan\anaconda3\lib\site-packages (41.0.1)

(base) C:\Users\rehan>conda activate nilmtk-env1

(nilmtk-env1) C:\Users\rehan>conda install -c nilmtk nilmtk
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nilmtk -> hmmlearn
  - nilmtk -> nilm_metadata

Current channels:

  - https://conda.anaconda.org/nilmtk/win-32
  - https://conda.anaconda.org/nilmtk/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by nipunbatra** [comment] 2019-05-22 04:18
I can confirm this issue.

![Screenshot from 2019-05-22 09-47-25](https://user-images.githubusercontent.com/60985/58147111-a81d7a00-7c76-11e9-8eda-e900d174a543.png)

We are on to this and will resolve this soon.

**Comment by RehanLiaqat** [comment] 2019-05-22 04:37
Thanks

--
Best Regards,

Engr. Rehan Liaqat
Lecturer
Dept. of Electrical Engineering
Government College University, Faisalabad,,
Pakistan.

+92 331 4414489

**Comment by ayushp20** [comment] 2019-05-22 04:44
This is happening because of conda-forge not being on the list of channels to be searched.
Before installing nilmtk, enter:
`conda config --add channels conda-forge `
then continue with the above installation process.
hmmlearn is available specifically on conda-forge channel, which was the cause of this issue.
I'll add this step to the new installation documentation.

**Comment by nipunbatra** [comment] 2019-05-22 06:47
@RehanLiaqat We tried on a fresh Windows install and were able to get NILTMK working. Please seeL https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md

I'm closing the issue. Please reopen if you face problems.

**Closed** 2019-05-22 16:16 UTC

**Comment by PMeira** [comment] 2019-06-28 04:12
@ayushp20 @nipunbatra The hmmlearn package from conda-forge hasn't been updated for a while, so we're back to the same issue as before. It's probably a bad idea to use it in the long term. 

As we should move to Pomegranate later, we can keep it for a while. Note that since hmmlearn is the only thing we need from conda-forge, it would be better to drop it and use the official channels for most dependencies.

**Comment by nipunbatra** [comment] 2019-06-28 04:19
@PMeira 
@Rithwikksvr spent a lot of effort with Pomergranate and ported the entire code, but, found it to be very slow compared to hmmlearn.

**Comment by PMeira** [comment] 2019-06-28 04:45
@nipunbatra @Rithwikksvr That's a pity. There are more pressing issues, but we probably should provide hmmlearn binaries later, at least for Windows as I was doing on my channel.
