### ISSUE TITLE
Dataport converter broken / remove from NILMTK?

### ISSUE THREAD

**Issue by Shibumi497** [nilmtk/nilmtk#873] opened 2020-05-21 10:37 UTC
Hi everybody,

I would like to point out that the procedure to access to the Dataport dataset evolved : they ask an additional code they send by email.

In consequences, the dataport_downloader does not work anymore.
I would like to request some help to fix it.

Thanks in advance,

**Comment by PMeira** [comment] 2020-08-20 02:14
It's better to just remove the converter from NILMTK. Unless the converter is trivial, it makes more sense to start an external project that uses NILMTK instead of embedding it. As you can see, there's not much activity here to support a third-party commercial product like Dataport that barely contributed anything (AFAIK).

For me, Dataport was always really slow to the point that it was the hardest dataset to test. The authentication requirements also is an issue since we can't automate that.

**Comment by levaphenyl** [comment] 2020-08-24 07:09
I confirm Pecan Street as changed their policy. Academics user don't have any "Database access", i.e. can't use the downloader.
I wrote a converter for myself last week to get a `nilm_metadata`-compatible HDF file from the "flat files" (CSV).

Do you believe it is worth a PR?

**Comment by PMeira** [comment] 2020-08-25 01:31
@levaphenyl That's worse than I imagined as we would need to provide and maintain 2 converters for a commercial product.

There's also another PR open (but based on the 0.3.x branch). The issue is that I personally don't have time to track Pecan Street's changes, and test the converter regularly (besides recreating an account there, waiting for approval, etc.). If anyone else from the current contributors take the responsibility to maintain it on the long term, great. Besides testing, I never really used or had any interested whatsoever in the dataset, especially with the license changes. Otherwise, I really think it's better for the community to do it's thing:
- you could start a minimal repo for just the converter (if it contains just a single .py and the license, that's enough)
- we could then remove the current broken converter and add a link to yours in the documentation (maybe even warn through the code)
- of course, I don't expect you (or anyone in the community) to maintain that forever either. When you finish using it or move on to other projects, just archive the repository (GitHub adds an explicit banner about this).
- if someone else really needs to use PS and the converter is broken, they can fork the repo and update it. 

For a living dataset like this, I believe it really would be better for the authors of the dataset to maintain a converter, if they have any interest that NILMTK users consume it.

For archived datasets, the authors of the datasets usually abandon them after a year or two. It's better to leave the converters at NILMTK as they can get at least a chance of being maintained.

**Comment by levaphenyl** [comment] 2020-08-25 08:19
> There's also another PR open (but based on the 0.3.x branch).

Damned. I reinvented the wheel. Again.

Looking at the code in the PR, it is not enough to generate a proper dataset, as the CSV row are *not* sorted by increasing timestamp. You end up with the good old problem of sorting a file that does not fit in memory...
Thus, in my opinion, the existing PR is also obsolete.

You are right to put the responsibility on the dataset provider, especially if they change the API regularly.
There are 2 solutions in my opinion:
1. You create a new repo under the `nilmtk` project, e.g `nilmtk/dataport2nilmtk`, and then I create a PR with my converter. I prefer the converter to stay in the project rather than on my personal account.
2. I open a PR on Pecan Street's [repo](https://github.com/Pecan-Street/DataPort-Examples) with my converter.

In both solutions, Dataport converter and downloader are removed from `nilmtk` and a link to the new path is given.

NB: The converter code does not solve the problem of the OP as the issue was about the download through Database Access.

**Comment by PMeira** [comment] 2020-08-26 17:51
@levaphenyl Thank you for looking further.

> I reinvented the wheel. Again.

Sorry about that. I was aware that Pecan Street had changed the license and so on, but not the CSV vs. DB part.

> 1. You create a new repo under the nilmtk project, e.g nilmtk/dataport2nilmtk, and then I create a PR with my converter. I prefer the converter to stay in the project rather than on my personal account.
> 2. I open a PR on Pecan Street's repo with my converter.

I'd be fine with either. I wasn't aware of https://github.com/Pecan-Street/DataPort-Examples and, yeah, that'd be a good place indeed.

@nipunbatra Any thoughts on this? If you prefer a repo under NILMTK, note that you'd need to create the initial repo and set the permissions.

**Comment by levaphenyl** [comment] 2020-08-27 06:08
> Sorry about that. I was aware that Pecan Street had changed the license and so on, but not the CSV vs. DB part.

@PMeira No problem, it was said jokingly ;). 

Please notify me when you made a decision!

**Comment by PMeira** [comment] 2020-09-04 21:57
> I open a PR on Pecan Street's repo with my converter.

@levaphenyl Could you please try that? 

In case that doesn't work, I guess we just keep it here in the NILMTK repo and document that we removed the DB variant of the converter due to its nature.

**Comment by levaphenyl** [comment] 2020-09-14 11:36
@PMeira I opened an issue [on the Dataport repo](https://github.com/Pecan-Street/DataPort-Examples/issues/1) polling the interest of Pecan Street before opening any PR.

**Comment by oneway3124** [comment] 2020-12-13 06:19
@Shibumi497 Can you share the dataport dataset before this change

**Comment by PMeira** [comment] 2020-12-31 05:57
@oneway3124 The full PS Dataport dataset was (is?) provided through a DB connection, it's probably terabytes of data. That's one reason why it was never tested throughly. You shouldn't be able to find it anywhere else since that's against their license.

@levaphenyl What are your thoughts on this now? Would you like to keep your CSV-only converter here?

**Comment by levaphenyl** [comment] 2021-01-12 06:53
I never had any answer from Pecan Street.

The problem with Pecan Street is the variability in the data format:
- University (free) users can download demo data in CSV format,
- Commercial licence users can access a SQL database, hence the relevance of the current converter,
- Companies can also pay one-time and get CSV data.

The other problem with Dataport data is the reproductibility. Any researcher using their data will in fact use different time frames of data (and different homes?). This will appear as "Pecan Street's Dataport" in the literature but the underlying experiment is different.
On the other hand, Dataport is pretty unique in terms of completeness and it would be a waste no to use it for NILM.

I just pinged Pecan Street again, at least to have an answer on their position regarding this.
In case they refuse to maintain converters, I believe the best approach is to provide scripts ourselves and state clearly that they come without guarranty and that users should adapt them to their needs.

**Comment by BRCH5** [comment] 2021-08-04 11:59
Hi everyone,

I was wondering if there are any updates on this issue?
Is a PR with a new CSV-HDF Dataport converter still being considered?

Thanks :)

**Comment by levaphenyl** [comment] 2021-10-15 07:54
@BRCH5, sorry for the delay.
If opened a PR (https://github.com/nilmtk/nilmtk/pull/941) with my code, at last.
I haven't run this script in a year. Can you please check with the latest Dataport sample?

If it works for you, I will merge.

**Comment by PiaDiepman** [comment] 2021-11-16 10:32
@levaphenyl  Thank you for uploading that script.
I have 1 min dataport data up to 2019 but unfortunately the script didn't work for me.
It did generate a HDF5 file, however only 3KB in size so the data wasn't converted properly.
I haven't been able to put much time into it recently but I'll try take another look at it over the coming weeks.
Have you been able to run the script since creating the pull request?

**Comment by BRCH5** [comment] 2021-11-16 10:37
Thank you for uploading that script.
I have 1 min dataport data up to 2019 but unfortunately the script didn't work for me.
It did generate a HDF5 file, however only 3KB in size so the data wasn't converted properly.
I haven't been able to put much time into it recently but I'll try take another look at it over the coming weeks.
Have you been able to run the script since creating the pull request?

**Comment by levaphenyl** [comment] 2021-11-17 08:18
@BRCH5, what are your folder and file names? Have you adapted the states and the paths in the `__main__` part of the script?

**Comment by BRCH5** [comment] 2021-11-17 16:35
@levaphenyl I am trying to convert three months of data with a file path as follows: 'C:/Users/XX/Documents/NILMTK/Dataport/2016/1min_july2016.csv'. (same path for the two other months)
Yes, I have edited the __main__ part of the script to match my file and folder names..

**Comment by levaphenyl** [comment] 2021-11-18 07:49
@BRCH5, thank you for the feedback. I updated the script to simplify it (remove filtering by US state).
It ran successfully on my computer and the 1s data from Austin.
You can check the latest version on the PR.

If your `metadata.csv` file is correct, you should see the following message in the console while it is processing:
```
Looking for building XX.
```
If it still doesn't work for you, please share your `__main__` section and the console output.

**Comment by BRCH5** [comment] 2021-11-18 16:45
@levaphenyl Thank you for getting back to me again so quickly!
Yes I do see 'Looking or building XX' when I run the script and the script runs to completion but the HDF5 contains no data.

For me, the converter seems to have an issue when it enters 'extract_building_data'.
It returns an empty dataframe for b_data.
I am getting a FutureWarning for line if _b_id in csv_chunk["dataid"].values:_ in the code which is in 'extract_building_data'
Do you get the same warning?
I have attached screenshots of my console and __main__ as requested.

![Console](https://user-images.githubusercontent.com/88436702/142457340-c16ad3c1-cb1c-492c-ac4b-9bf3cb18b354.JPG)
![main](https://user-images.githubusercontent.com/88436702/142457347-3798e41c-cfca-4b24-82fa-2f4a1f2233fd.JPG)

**Comment by levaphenyl** [comment] 2021-11-22 08:21
@BRCH5 - Interesting! I don't see the `FutureWarning`.

I updated the script to explicitly assign the type of `b_id`. Latest version here: https://github.com/nilmtk/nilmtk/pull/941/commits/1d60698d8e58a46f27fe879a6a125399e969d31b.

Does it work for you now?
If it doesn't, please share with me your versions of `python`, `numpy` and `pandas`.

**Comment by BRCH5** [comment] 2021-12-06 09:28
@levaphenyl Apologies for the delay in getting back, I haven't been able to put much time into NILMTK in recent weeks.
The new version of the converter, 1d60698, works for me!

As a final check to see if the dataset had been converted properly, I tried to run the elecmeter_and_metergroup notebook and also a simple experiment using the API with the .h5 file. Unfortunately, neither would run.

Have you been able to run any notebooks with .h5 files created using the new converter?

**Comment by levaphenyl** [comment] 2022-06-04 13:32
@BRCH5 It is my turn to apologize for the delay!

I created a test `.h5` file using my script and the Dataport CSVs. Using the same code as in [elecmeter_and_metergroup.ipynb](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/elecmeter_and_metergroup.ipynb), I was able to load data and compute the fraction per meter.

Consequently, I will close this and merge. Please, feel free to open a new ticket with your specific error and tag me if the problem persists on your side.

**Closed by levaphenyl** 2022-06-04 13:32 UTC
Labels: enhancement, DataStore and format conversion
