### ISSUE TITLE
convert_redd is failing

### ISSUE THREAD

**Issue by vmanish** [nilmtk/nilmtk#830] opened 2019-10-21 11:56 UTC
Getting below error

ValueError: The file '/data/REDD/redd.h5' is already opened.  Please close it before reopening in write mode.

my jupyter notebook is inside an ubuntu docker on windows hyperV host.

Steps to reproduce
----------------------
1> Installed ubuntu docker with docker pull ubuntu command on windows 10 running Hyper-V and docker desktop 2.1.0.1 stable.
2> Installed nilmtk following steps mentioned  in docs/manual/user_guide/install_user.md
3> downloaded REDD dataset 
4> ran following python steps from docs/manual/user_guide/data.ipynb
{{
from nilmtk.dataset_converters import convert_redd
convert_redd('/data/REDD/low_freq', '/data/redd.h5')
}}

Got following error:-
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-60345b34f7a6> in <module>
      1 from nilmtk.dataset_converters import convert_redd
----> 2 convert_redd('/data/REDD/low_freq','/data/REDD/redd.h5')

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/nilmtk/dataset_converters/redd/convert_redd.py in convert_redd(redd_path, output_filename, format)
     39 
     40     # Open DataStore
---> 41     store = get_datastore(output_filename, format, mode='w')
     42 
     43     # Convert raw data to DataStore

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/nilmtk/utils.py in get_datastore(filename, format, mode)
    320     if filename is not None:
    321         if format == 'HDF':
--> 322             return HDFDataStore(filename, mode)
    323         elif format == 'CSV':
    324             return CSVDataStore(filename)

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/nilmtk/docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/nilmtk/datastore/hdfdatastore.py in __init__(self, filename, mode)
     28             warnings.filterwarnings('ignore', category=RuntimeWarning, message='.*numpy.ufunc size changed.*')
     29 
---> 30             self.store = pd.HDFStore(filename, mode, complevel=9, complib='blosc')
     31             super(HDFDataStore, self).__init__()
     32 

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    486         self._fletcher32 = fletcher32
    487         self._filters = None
--> 488         self.open(mode=mode, **kwargs)
    489 
    490     def __fspath__(self):

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    627                             hdf_version=tables.get_hdf5_version()))
    628 
--> 629             raise e
    630 
    631         except (Exception) as e:

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    601 
    602         try:
--> 603             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    604         except (IOError) as e:  # pragma: no cover
    605             if 'can not be written' in str(e):

~/anaconda3/envs/nitlmktenv/lib/python3.6/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    310                 raise ValueError(
    311                     "The file '%s' is already opened.  Please "
--> 312                     "close it before reopening in write mode." % filename)
    313 
    314     # Finally, create the File instance, and return it

ValueError: The file '/data/REDD/redd.h5' is already opened.  Please close it before reopening in write mode.

**Comment by PMeira** [comment] 2019-10-21 12:05
Please document the minimal steps to reproduce what you're doing. Right now I consider the message pretty clear...

**Comment by vmanish** [comment] 2019-10-22 04:53
@PMeira updated earlier comments with steps & error

**Comment by Boldyshev** [comment] 2019-10-24 15:12
I have the same issue on Windows 10, it's fine on Ubuntu 18.04.2

**Comment by PMeira** [comment] 2019-10-24 16:45
@vmanish @Boldyshev So... it's working fine on my side, even inside docker. I'd recommend checking file permissions and so on -- e.g. is there any other process, such as an antivirus, another Python instance, etc. accessing the file? If the file exists, try removing it first.

As you can see from the traceback, the issue is raised inside pytables. You might want to try it directly: https://www.pytables.org/usersguide/tutorials.html#creating-a-pytables-file-from-scratch

You can also try to install without using conda-forge using my channel instead -- this would use most of the official/main conda packages instead of the conda-forge ones:
```
conda create -n nilmtk-env2 -c nilmtk -c pmeira nilmtk
```

I tested both ways, with conda-forge and with channel, both working fine. So, yeah, it's an issue with your local environments, permissions, etc., it's not related to NILMTK.

**Comment by PMeira** [comment] 2019-11-04 12:21
Closing since I could not reproduce and there have been no new reports. Reopen if necessary.

**Closed by PMeira** 2019-11-04 12:21 UTC
Labels: DataStore and format conversion, support

**Comment by Shibumi497** [comment] 2020-02-26 17:02
Hi,

I have exactly the same problem, to install with your channel didn't change anything...

![Screenshot 2020-02-26 at 18 02 39](https://user-images.githubusercontent.com/60926736/75368515-2ec84d00-58c2-11ea-8276-40323131ac78.png)

Thanks in advance

**Comment by PMeira** [comment] 2020-04-03 06:27
@Shibumi497 Permission issues, most likely. Just putting the HDF output in another folder tha your user has write access is probably enough.

By the way, try to avoid commenting on closed issues here on GitHub as they don't trigger notifications the same way as open issues.
