### ISSUE TITLE
Error in Applying metric RMSE, FSCORE on CO result and Applying FHMM algorithm

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#370] opened 2015-03-29 14:15 UTC
Hi guys :)
We have continued to work on our data since you said that we can use our data containing only the
Power Active variable. We managed to do the CO algorithm with a 5 minutes resolution. But we have some issues to apply the metric RMSE and FSCORE on the CO results. We put some pictures here : 
![error_rmse](https://cloud.githubusercontent.com/assets/10998195/6885951/1cfb3488-d62d-11e4-8647-44158a9b126d.png)
![error_metric_fscore_1](https://cloud.githubusercontent.com/assets/10998195/6885952/2260ddb0-d62d-11e4-9c1c-3858dec058cb.png)
![error_metric_fscore_2](https://cloud.githubusercontent.com/assets/10998195/6885953/28014a20-d62d-11e4-8ea3-0c5af08b3d80.png)
We have also some errors with the FHMM desagregation : 
![fhmm_error1](https://cloud.githubusercontent.com/assets/10998195/6885983/99e49f38-d62e-11e4-8614-6a1df03f3972.png)
![fhmm_error2](https://cloud.githubusercontent.com/assets/10998195/6885987/a5d27694-d62e-11e4-860b-4098fa99da53.png)

Sorry for our all questions all the day long loool
Thanks guys :)

**Comment by nipunreddevil** [comment] 2015-03-29 14:18
I suspect that in both the cases there is no data to disaggregate. 

Can you do the following?

```python
df = disag_elec.load().next()
print df.describe()
```

**Comment by GautierAppert** [comment] 2015-03-29 14:21
![df_1](https://cloud.githubusercontent.com/assets/10998195/6886015/8835e3e0-d62f-11e4-8b27-9a52dc7a8c29.png)
![df_2](https://cloud.githubusercontent.com/assets/10998195/6886016/8d447ef0-d62f-11e4-807c-ddc5e20b3854.png)

It seems that there are some issues
thanks again :)

**Comment by GautierAppert** [comment] 2015-03-29 14:25
And the CO results : 
![co_results](https://cloud.githubusercontent.com/assets/10998195/6886020/1719452a-d630-11e4-84a1-3a7ea12dcd7e.png)
We don't very much anderstand... looooool
Thanks again

**Comment by JackKelly** [comment] 2015-03-30 19:16
@GautierAppert regarding your 'Level physical_quantity not found' error: are you sure you call `df.column.set_names(LEVEL_NAMES, inplace=True)` in your dataset converter?  i.e. like in [line 187 of convert_redd.py](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/redd/convert_redd.py#L187)?

**Comment by GautierAppert** [comment] 2015-04-03 15:47
Hi guys :)
We think that we have tried your line of code.
Here is a part of our data set converter :+1:
![converter](https://cloud.githubusercontent.com/assets/10998195/6984422/ee2edb28-da28-11e4-9289-851a99ecd521.png)
We think that it might be due to some values which are very small (close to zero) but we are not very sure and maybe it can be due to our 5 minutes frequency.
Thanks again for your help :)

**Comment by GautierAppert** [comment] 2015-04-03 20:36
Hi guys :)
We have finally manage to apply the desagregation using FHMM and CO. In fact we have aggregated our data to 1 minutes instead of 5 minutes. And now everything seems to work... (we don't know if it is really due to the aggregation to 1 minutes of our data..).
Here are some pictures of our results :+1: 
![disag_co_new_frequency_1min](https://cloud.githubusercontent.com/assets/10998195/6988389/3cd3bd7a-da51-11e4-916c-699982417c80.png)
![rmse_co](https://cloud.githubusercontent.com/assets/10998195/6988393/459b09e0-da51-11e4-8f95-c2a792738f76.png)
![fhmm_disag_new_frequency_1min](https://cloud.githubusercontent.com/assets/10998195/6988398/4ad8d748-da51-11e4-82f3-a236b8d467d5.png)
![rmse_fhmm](https://cloud.githubusercontent.com/assets/10998195/6988399/4f699b30-da51-11e4-9b17-fb08573b9373.png)
However we are wondering why in the desagregation result there is not the aggregate meter (called site meter) reported in the result. In fact it is not very important but maybe it is related to the error mentioned before.
Thanks for all your help :)
Have a good night and geek nigth :)

**Comment by JackKelly** [comment] 2015-04-09 14:59
> why in the desagregation result there is not the aggregate meter (called site meter) reported in the result.

That's by design, I think.  We only show the disaggregated appliances in the appliance estimates.  Or did I not understand your question correctly?

I'll close this issue for now.  Please re-open if needs be.

**Closed by JackKelly** 2015-04-09 14:59 UTC
