### ISSUE TITLE
ValueError during FHMM disaggregation

### ISSUE THREAD

**Issue by jhyun0919** [nilmtk/nilmtk#478] opened 2016-01-28 10:34 UTC
I have an issue that ValueError keep occurring during FHMM disaggregation.

There is no error in my CO disaggregation scenario.

I want to compare those two disaggregation procedures and to choose the better one.

Could you give me an advice or point out how to solve the issue?

---

``` python
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: from os.path import join

In [4]: 

In [4]: from pylab import rcParams

In [5]: import matplotlib.pyplot as plt

In [6]: %matplotlib

(process:6415): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:6415): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:6415): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Using matplotlib backend: Qt4Agg

In [7]: rcParams['figure.figsize'] = (14, 6)

In [8]: plt.style.use('ggplot')

In [9]: import nilmtk
/root/nilmtk/nilmtk/node.py:2: ImportWarning: Not importing directory 'nilm_metadata': missing __init__.py
  from nilm_metadata import recursively_update_dict

In [10]: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore

In [11]: from nilmtk.disaggregate import CombinatorialOptimisation

In [12]: from nilmtk.disaggregate import fhmm_exact

In [13]: import time

In [14]: from nilmtk.utils import print_dict

In [15]: from nilmtk.metrics import f1_score

In [16]: 

In [16]: import warnings

In [17]: warnings.filterwarnings("ignore")

In [18]: 

In [18]: 

In [18]: 

In [18]: # LOADING DATA

In [19]: 

In [19]: data_dir = '/data/REDD/'

In [20]: 

In [20]: train_set = DataSet(join(data_dir, 'redd.h5'))

In [21]: print('loaded ' + str(len(train_set.buildings)) + ' buildings')
loaded 6 buildings

In [22]: 

In [22]: test_set = DataSet(join(data_dir, 'redd.h5'))

In [23]: print('loaded ' + str(len(test_set.buildings)) + ' buildings')
loaded 6 buildings


In [27]: # EXAMINE METADATA FOR A SINGLE HOUSE

In [28]: 

In [28]: building_number = 3

In [29]: train_set.buildings[building_number].metadata
Out[29]: {'dataset': 'REDD', 'instance': 3, 'original_name': 'house_3'}

In [30]: test_set.buildings[building_number].metadata
Out[30]: {'dataset': 'REDD', 'instance': 3, 'original_name': 'house_3'}

In [31]: 

In [31]: 

In [31]: 

In [31]: train_set.set_window(end='2011-04-24 00:00:00')

In [32]: test_set.set_window(start='2011-04-25 00:00:00', end='2011-04-27 00:00:00')

In [33]: 

In [33]: train_elec = train_set.buildings[building_number].elec

In [34]: test_elec = test_set.buildings[building_number].elec
```

---

CO Disaggregation

``` python
In [35]: # Train

In [36]: 

In [36]: start = time.time()

In [37]: 

In [37]: co = CombinatorialOptimisation()

In [38]: co.train(train_elec)
Training model for submeter 'ElecMeter(instance=3, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=5, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=3, dataset='REDD', appliances=[Appliance(type='CE appliance', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=3, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=3, dataset='REDD', appliances=[Appliance(type='waste disposal unit', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=3, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=3, dataset='REDD', appliances=[Appliance(type='electric furnace', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=2)])'
Training model for submeter 'ElecMeter(instance=12, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=3)])'
Training model for submeter 'ElecMeter(instance=15, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=3)])'
Training model for submeter 'ElecMeter(instance=16, building=3, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=17, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=4)])'
Training model for submeter 'ElecMeter(instance=18, building=3, dataset='REDD', appliances=[Appliance(type='smoke alarm', instance=1)])'
Training model for submeter 'ElecMeter(instance=19, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=5)])'
Training model for submeter 'ElecMeter(instance=20, building=3, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=21, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=4)])'
Training model for submeter 'ElecMeter(instance=22, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=5)])'
Training model for submeter 'MeterGroup(meters=
  ElecMeter(instance=13, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=14, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
)'
Loading data for meter ElecMeterID(instance=14, building=3, dataset='REDD')     
Done loading data all meters for this chunk.
Done training!

In [39]: 

In [39]: end = time.time()

In [40]: print("Runtime =", end-start, "seconds.")
('Runtime =', 2.7749547958374023, 'seconds.')

In [41]: # Disaggregate

In [42]: 

In [42]: disag_filename = join(data_dir, 'co_redd-disag.h5')

In [43]: output = HDFDataStore(disag_filename, 'w')

In [44]: co.disaggregate(test_elec.mains(), output)
Loading data for meter ElecMeterID(instance=2, building=3, dataset='REDD')     
Done loading data all meters for this chunk.
Including vampire_power = 122.31199646 watts to model...
Estimating power demand for 'ElecMeter(instance=3, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Estimating power demand for 'ElecMeter(instance=5, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=3, dataset='REDD', appliances=[Appliance(type='CE appliance', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=3, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Estimating power demand for 'ElecMeter(instance=8, building=3, dataset='REDD', appliances=[Appliance(type='waste disposal unit', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=3, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=3, dataset='REDD', appliances=[Appliance(type='electric furnace', instance=1)])'
Estimating power demand for 'ElecMeter(instance=11, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=2)])'
Estimating power demand for 'ElecMeter(instance=12, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=3)])'
Estimating power demand for 'ElecMeter(instance=15, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=3)])'
Estimating power demand for 'ElecMeter(instance=16, building=3, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=17, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=4)])'
Estimating power demand for 'ElecMeter(instance=18, building=3, dataset='REDD', appliances=[Appliance(type='smoke alarm', instance=1)])'
Estimating power demand for 'ElecMeter(instance=19, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=5)])'
Estimating power demand for 'ElecMeter(instance=20, building=3, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
Estimating power demand for 'ElecMeter(instance=21, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=4)])'
Estimating power demand for 'ElecMeter(instance=22, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=5)])'
Estimating power demand for 'MeterGroup(meters=
  ElecMeter(instance=13, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=14, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
)'

In [45]: output.close()

In [46]: 
```

---

FHMM Disaggregation -> ValueError

``` python

In [46]: # TRAINING AND DISAGGREGATION - FHMM

In [47]: 

In [47]: # Train

In [48]: 

In [48]: start = time.time()

In [49]: 

In [49]: fhmm = fhmm_exact.FHMM()

In [50]: fhmm.train(train_elec)
Training model for submeter 'ElecMeter(instance=3, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=3, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=5, building=3, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=3, dataset='REDD', appliances=[Appliance(type='CE appliance', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=3, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=3, dataset='REDD', appliances=[Appliance(type='waste disposal unit', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=3, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=3, dataset='REDD', appliances=[Appliance(type='electric furnace', instance=1)])'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-50-8dc9e07f8a30> in <module>()
----> 1 fhmm.train(train_elec)

/root/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in train(self, metergroup, num_states_dict, **load_kwargs)
    281 
    282             # Fit
--> 283             learnt_model[meter].fit([X])
    284 
    285             # Check to see if there are any more chunks.

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/hmmlearn/hmm.pyc in fit(self, obs)
    326         more training data, or increasing covars_prior.
    327         """
--> 328         return super(GaussianHMM, self).fit(obs)
    329 
    330 

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/hmmlearn/base.pyc in fit(self, obs)
    375             curr_logprob = 0
    376             for seq in obs:
--> 377                 framelogprob = self._compute_log_likelihood(seq)
    378                 lpr, fwdlattice = self._do_forward_pass(framelogprob)
    379                 bwdlattice = self._do_backward_pass(framelogprob)

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/hmmlearn/hmm.pyc in _compute_log_likelihood(self, obs)
    183     def _compute_log_likelihood(self, obs):
    184         return log_multivariate_normal_density(
--> 185             obs, self._means_, self._covars_, self._covariance_type)
    186 
    187     def _generate_sample_from_state(self, state, random_state=None):

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/sklearn/mixture/gmm.pyc in log_multivariate_normal_density(X, means, covars, covariance_type)
     63         'full': _log_multivariate_normal_density_full}
     64     return log_multivariate_normal_density_dict[covariance_type](
---> 65         X, means, covars)
     66 
     67 

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/sklearn/mixture/gmm.pyc in _log_multivariate_normal_density_full(X, means, covars, min_covar)
    707                                           lower=True)
    708             except linalg.LinAlgError:
--> 709                 raise ValueError("'covars' must be symmetric, "
    710                                  "positive-definite")
    711 

ValueError: 'covars' must be symmetric, positive-definite
```

**Comment by nipunbatra** [comment] 2016-01-28 10:36
Are you able to run the FHMM code that we've provided in sample notebook?

**Comment by JackKelly** [comment] 2016-01-28 10:40
@jhyun0919 also, please can you tell us which versions you're using?  Please can you run `from nilmtk.utils import show_versions; show_versions()` and copy and paste the output into this issue queue?

**Comment by jhyun0919** [comment] 2016-01-28 10:48
@nipunbatra 
Yes, it runs well.
```python
In [1]: from __future__ import print_function, division

In [2]: import time

In [3]: from matplotlib import rcParams

In [4]: import matplotlib.pyplot as plt

In [5]: %matplotlib

(process:21607): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:21607): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:21607): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Using matplotlib backend: Qt4Agg

In [6]: rcParams['figure.figsize'] = (13, 6)

In [7]: plt.style.use('ggplot')

In [8]: 

In [8]: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
/root/nilmtk/nilmtk/node.py:2: ImportWarning: Not importing directory 'nilm_metadata': missing __init__.py
  from nilm_metadata import recursively_update_dict

In [9]: from nilmtk.disaggregate import CombinatorialOptimisation

In [10]: 

In [10]: train = DataSet('/data/REDD/redd.h5')

In [11]: test = DataSet('/data/REDD/redd.h5')

In [12]: building = 1

In [13]: train.set_window(end="30-4-2011")

In [14]: test.set_window(start="30-4-2011")

In [15]: 

In [15]: 

In [15]: train_elec = train.buildings[1].elec

In [16]: test_elec = test.buildings[1].elec

In [17]: top_5_train_elec = train_elec.submeters().select_top_k(k=5)
2/16 ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance3/16 ElecMeter(instance=7, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)]4/16 ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)]6/16 ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=7/16 ElecMeter(instance=12, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)8/16 ElecMeter(instance=13, building=1, dataset='REDD', appliances=[Appliance(type='electric space heater9/16 ElecMeter(instance=14, building=1, dataset='REDD', appliances=[Appliance(type='electric stove', inst10/16 ElecMeter(instance=15, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=311/16 ElecMeter(instance=16, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=412/16 ElecMeter(instance=17, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=2)]13/16 ElecMeter(instance=18, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=3)]14/16 ElecMeter(instance=19, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=215/16 MeterGroup(meters=
  ElecMeter(instance=3, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
  ElecMeter(instance=4, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
16/16 MeterGroup(meters= for ElecMeterID(instance=4, building=1, dataset='REDD') ...   
  ElecMeter(instance=10, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=20, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
Calculating total_energy for ElecMeterID(instance=20, building=1, dataset='REDD') ...   
In [18]: start = time.time()

In [19]: from nilmtk.disaggregate import fhmm_exact

In [20]: fhmm = fhmm_exact.FHMM()

In [21]: # Note that we have given the sample period to downsample the data to 1 minute

In [22]: fhmm.train(top_5_train_elec, sample_period=60)
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'

In [23]: end = time.time()

In [24]: print("Runtime =", end-start, "seconds.")
Runtime = 15.2449631691 seconds.

In [25]: disag_filename = '/data/REDD/redd-disag-fhmm.h5'

In [26]: output = HDFDataStore(disag_filename, 'w')

In [27]: # Note that we have mentioned to disaggregate after converting to a sample period of 60 seconds

In [28]: fhmm.disaggregate(test_elec.mains(), output, sample_period=60)
/root/nilmtk/nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.

In [29]: output.close()

In [30]: 


```
@JackKelly 
```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-25-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.21.2
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 3.1.0
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
bottleneck: None
tables: 3.2.2
numexpr: 2.3.1
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.2
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
None

Date: 2016-01-28 19:44:14.812272
Platform: Linux-3.19.0-25-generic-x86_64-with-debian-jessie-sid
System version: 2.7
nilmtk version: 0.2.0.dev-47c110e
nilm_metadata version: 0.2.0.dev-000207d
numpy version: 1.10.1
matplotlib version: 1.4.3
pandas version: 0.16.2
sklearn version: 0.17
hmmlearn version: 0.1.1
```

**Comment by nipunbatra** [comment] 2016-01-28 10:52
I am able to reproduce this error. This occurs because the HMM implementation (HMMlearn) is not able to learn the HMM params for electric furnace.
Can you please try learning these parameters outside of nilmtk?

```python
ef = ef = train_elec[('electric furnace',1)].load().next()
```

This gives us a Pandas dataframe. Now, please refer to HMMlearn documentation and try and fit an HMM to this data and let us know how it goes.

**Comment by PMeira** [comment] 2018-09-09 22:51
Closing, seems to work now, probably fixed with the updates. Beware it'll eat a lot of memory though...

**Closed by PMeira** 2018-09-09 22:51 UTC
