### ISSUE TITLE
AttributeError: Attribute 'metadata' does not exist in node: '/' 

### ISSUE THREAD

**Issue by ro269** [nilmtk/nilmtk#531] opened 2016-11-21 06:48 UTC
After running the following piece of code:
disag_co=DataSet(disag_filename)

I am getting the following error:
AttributeError: Attribute 'metadata' does not exist in node: '/' 

I've` seen #373  , however the solution to that(modified metergroup function) is already been taken care off in my version of nilmtk. Still, I'm getting this error. 
Please help.

**Comment by nipunbatra** [comment] 2017-01-12 14:34
What OS are you using?

**Comment by nipunbatra** [comment] 2017-01-21 04:53
@ro269 : Please help us reproduce this bug, else we'll close it.

**Comment by WangChunyi** [comment] 2017-03-22 11:15
from nilmtk import DataSet

redd = DataSet('C:/Users/Wang/Anaconda3\Lib/site-packages/nilmtk/data/REDD/redd.h5')

Traceback (most recent call last):

  File "<ipython-input-3-313391409cb2>", line 3, in <module>
    redd = DataSet('C:/Users/Wang/Anaconda3\Lib/site-packages/nilmtk/data/REDD/redd.h5')

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\dataset.py", line 46, in __init__
    self.import_metadata(get_datastore(filename, format))

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\dataset.py", line 55, in import_metadata
    self.metadata = store.load_metadata()

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\datastore\hdfdatastore.py", line 176, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\tables\attributeset.py", line 288, in __getattr__
    "'%s'" % (name, self._v__nodepath))

AttributeError: Attribute 'metadata' does not exist in node: '/'

I also have the problem, my OS is window7. can you help me?thank you

**Comment by nipunbatra** [comment] 2017-03-22 11:20
This may be due to incorrect dataset conversion. Can you try converting the REDD dataset again and report the output?

**Comment by WangChunyi** [comment] 2017-03-23 12:26
I try converting the REDD dataset again, but I also have the problem. can you help me analysis can you analysis the problem? thank you.
from nilmtk.utils import print_dict
C:\Users\Wang\Anaconda3\lib\importlib\_bootstrap.py:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

from nilmtk.dataset_converters import convert_redd

convert_redd('C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/low_freq', 'C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/REDD/redd.h5')
Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 2... 1 2 3 4 5 6 7 8 9 10 11 
Loading house 3... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
Loading house 4... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 5... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 
Traceback (most recent call last):

  File "<ipython-input-3-91615c7f3c8c>", line 1, in <module>
    convert_redd('C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/low_freq', 'C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/REDD/redd.h5')

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py", line 51, in convert_redd
    store)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py", line 78, in save_yaml_to_datastore
    meter_devices = _load_file(yaml_dir, 'meter_devices.yaml')

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py", line 105, in _load_file
    return yaml.load(fh)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()

  File "C:\Users\Wang\Anaconda3\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()

  File "C:\Users\Wang\Anaconda3\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)

UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1593: illegal multibyte sequence


from nilmtk import DataSet



redd = DataSet('C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/REDD/redd.h5')
Traceback (most recent call last):

  File "<ipython-input-5-3af594e14d5c>", line 1, in <module>
    redd = DataSet('C:/Users/Wang/Anaconda3/Lib/site-packages/nilmtk/data/REDD/redd.h5')

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\dataset.py", line 46, in __init__
    self.import_metadata(get_datastore(filename, format))

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\dataset.py", line 55, in import_metadata
    self.metadata = store.load_metadata()

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\nilmtk\nilmtk\datastore\hdfdatastore.py", line 176, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)

  File "C:\Users\Wang\Anaconda3\lib\site-packages\tables\attributeset.py", line 288, in __getattr__
    "'%s'" % (name, self._v__nodepath))

AttributeError: Attribute 'metadata' does not exist in node: '/'

**Comment by nipunbatra** [comment] 2017-03-24 06:34
You have the following error while converting:

```python

UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1593: illegal multibyte sequence
```

This isn't a NILMTK error. Please seem more [here](https://github.com/rkern/line_profiler/issues/37) to find directions on resolving this. Since this isn't NILMTK error, I am closing this.

**Closed by nipunbatra** 2017-03-24 06:34 UTC
