### ISSUE TITLE
CO/FHMM train and disaggregate with sample periods > 60

### ISSUE THREAD

**Issue by cklemenj** [nilmtk/nilmtk#431] opened 2015-09-10 21:23 UTC
Hi there,
i am starting to use NILMTK these days and i was going through the tutorials/documentation.
In  [Disaggregation and metrics] (https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb) i tried to adjust the sample period to see how a different sample period of the data impacts the f1_score. I I got the code from the tutorial.
```python
from __future__ import print_function, division
import time

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore

train = DataSet('/Users/christoph/RPNILM/nilmtk/data/REDD/redd.h5')
test = DataSet('/Users/christoph/RPNILM/nilmtk/data/REDD/redd.h5')

train.set_window(end="30-4-2011")
test.set_window(start="30-4-2011")

building = 1

train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

fridge_meter = train_elec['fridge']

fridge_df = fridge_meter.load().next()

mains = train_elec.mains()

mains_df = mains.load().next()

top_5_train_elec = train_elec.submeters().select_top_k(k=5)

top_5_train_elec

start = time.time()
from nilmtk.disaggregate import CombinatorialOptimisation
co = CombinatorialOptimisation()
# Note that we have given the sample period to downsample the data to 1 minute
co.train(top_5_train_elec, sample_period=90)
end = time.time()
print("Runtime =", end-start, "seconds.")

disag_filename = '/Users/christoph/RPNILM/nilmtk/data/REDD/redd-disag-co.h5'
output = HDFDataStore(disag_filename, 'w')
# Note that we have mentioned to disaggregate after converting to a sample period of 60 seconds
co.disaggregate(test_elec.mains(), output, sample_period=90)
output.close()

disag_co = DataSet(disag_filename)
disag_co_elec = disag_co.buildings[building].elec

from nilmtk.metrics import f1_score
f1_co= f1_score(disag_co_elec, test_elec)
f1_co.index = disag_co_elec.get_labels(f1_co.index)

print(f1_co)
```
which results in the following error:
```
Done loading data all meters for this chunk.
Traceback (most recent call last):
  File "/Users/christoph/RPNILM/nilmtk/scripts/CombOpt/co_issue.py", line 47, in <module>
    f1_co= f1_score(disag_co_elec, test_elec)
  File "/Users/christoph/RPNILM/nilmtk/nilmtk/metrics.py", line 234, in f1_score
    tot_samples)
  File "/Users/christoph/conda/lib/python2.7/site-packages/pandas/core/ops.py", line 532, in wrapper
    return left._constructor(wrap_results(na_op(lvalues, rvalues)),
  File "/Users/christoph/conda/lib/python2.7/site-packages/pandas/core/ops.py", line 485, in na_op
    result = com._fill_zeros(result, x, y, name, fill_zeros)
  File "/Users/christoph/conda/lib/python2.7/site-packages/pandas/core/common.py", line 1442, in _fill_zeros
    mask = ((y == 0) & ~np.isnan(result)).ravel()
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Closing remaining open files:/Users/christoph/RPNILM/nilmtk/data/REDD/redd-disag-co.h5...done/Users/christoph/RPNILM/nilmtk/data/REDD/redd.h5...done/Users/christoph/RPNILM/nilmtk/data/REDD/redd.h5...done

```
Do the co.train and co.disaggregate support sample periods bigger than 60?

i tried so with 90,120,900 and so on and all of those sample periods lead to this error message, sample periods smaller or equal 60 worked fine and f1_score was calculated correctly.

**Comment by JackKelly** [comment] 2015-09-11 05:17
Welcome to nilmtk!

Please can you run this code and show us the output :

```
from nilmtk.utils import show_versions
show_versions()
```

**Comment by cklemenj** [comment] 2015-09-11 07:16
```
nilmtk/utils.py:1: ImportWarning: Not importing directory 'hmmlearn': missing __init__.py
  from __future__ import print_function, division
nilmtk/utils.py:1: ImportWarning: Not importing directory '/Users/christoph/RPNILM/nilmtk/hmmlearn': missing __init__.py
  from __future__ import print_function, division

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: de_AT.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.22.1
numpy: 1.9.2
scipy: 0.16.0
statsmodels: None
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.1
pytz: 2015.4
bottleneck: 1.0.0
tables: 3.2.1.1
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
None

Date: 2015-09-11 09:14:07.868926
Platform: Darwin-14.5.0-x86_64-i386-64bit
System version: 2.7
nilmtk version: 0.2.0.dev-1756877
nilm_metadata version: 0.2.0.dev-bc88d86
numpy version: 1.9.2
matplotlib version: 1.4.3
pandas version: 0.16.2
sklearn version: 0.16.1
hmmlearn version: 0.1.1

````

**Comment by nipunreddevil** [comment] 2015-09-15 15:35
I tried `disag_elec.plot()` which worked correct. 
On running @cklemenj's script, I get the same error.

**Comment by JackKelly** [comment] 2015-09-18 10:54
I've replicated this bug too.  I'm working on it now...

**Comment by JackKelly** [comment] 2015-09-18 11:18
So, I think I've found the problem... I think the problem is that, for each pair of ground truth meters and each 'predicted meters', alignment of the indicies fails because the ground truth meters (in your `test_elec` object) have a sample period of 3 seconds but the sample period is 90 seconds in the 'predicted' meters.

I've modified the NILMTK code so it gives a warning instead of blowing up.

NILMTK is supposed to handle the resampling for you and I'm not sure why that isn't happening... I'll keep digging...

**Comment by JackKelly** [comment] 2015-09-18 11:37
OK, I think this bug is fixed now.  @cklemenj I can now run your script successfully on my machine :)

**Closed** 2015-09-18 11:37 UTC

**Comment by cklemenj** [comment] 2015-09-18 11:41
Thank you so much
