### ISSUE TITLE
plot_activity_histogram - ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>

### ISSUE THREAD

**Issue by anasvaf** [nilmtk/nilmtk#706] opened 2018-09-28 12:47 UTC
Hello, 
I have the following code snippet
```
import nilmtk
dataset = nilmtk.DataSet('ukdale.h5')
dataset.set_window("2013-03-01", None)
elec = dataset.buildings[1].elec # 54 appliances for house 1
num_appliances = 5
fig, axes = plt.subplots(num_appliances, 1)
meter_keys = ['kettle', 'dish washer', 'fridge', 'microwave', 'washing machine']
hist = elec.activity_histogram()
# axes = elec.plot_multiple(axes, meter_keys, 'plot_activity_histogram')
```

I want to plot the activity histogram for the selected appliances. However, I get the following error:
- ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>
 when calculating the activity histogram, the error is:
- AttributeError: 'numpy.float32' object has no attribute 'reindex'

I have seen in the past an issue raised with regards to the "activity_histogram" function about dtypes. I am not sure if they are related since the pandas version has changed. I am running it on an ubuntu 16.04 machine using python 3.5.2, pandas 0.23.4, matplotlib 3.0.0 and numpy 1.15.0
Any help would be appreciated.

Best Regards,
Tasos
![screenshot 2018-09-28 at 15 18 18](https://user-images.githubusercontent.com/23378874/46210736-db02ae80-c331-11e8-8e54-0f7aa2a3128b.png)

**Comment by PMeira** [comment] 2018-09-28 19:06
@anasvaf Thanks for the report, I can confirm the issue with Pandas 0.23. My recommendation is to use Pandas 0.22 for the moment, hence it is listed as such in https://github.com/nilmtk/nilmtk/blob/master/environment.yml

Side note: we'll probably skip Pandas 0.23 and upgrade to 0.24 since it should be released soon. It seems Pandas 0.25 will be the last release with major changes before Pandas 1.0, so the situation should be more stable soon.

**Comment by PMeira** [comment] 2018-09-28 20:16
@anasvaf Ah, sorry, it seems Pandas 0.22 doesn't fix all the issues in `activity_histogram`.

**Comment by ilia200** [comment] 2019-03-10 11:16
It seems I was able to get it to work.

in  def activity_histogram changed the following:
1. when_on = self.when_on(**kwargs)                           changed to: 
when_on = self.when_on(sample_period = int(offset_alias_to_seconds(bin_duration)))
2.matrix = on_chunk.reshape((-1, n_bins))                     changed to:
matrix = on_chunk.values.reshape((-1, n_bins))

**Comment by ayushp20** [comment] 2019-05-30 19:07
@ilia200 I can confirm this does seem to solve this problem on *REDD* and *ECO* datasets on pandas 0.24 but other issues seem to pop up for *GREEND* datasets.
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-9c97e1b32b09> in <module>
----> 1 elec.plot_activity_histogram()

~/nilmtk/nilmtk/electric.py in plot_activity_histogram(self, ax, period, bin_duration, plot_kwargs, **kwargs)
    716             ax = plt.gca()
    717         hist = self.activity_histogram(bin_duration=bin_duration,
--> 718                                        period=period, **kwargs)
    719         if plot_kwargs is None:
    720             plot_kwargs = {}

~/nilmtk/nilmtk/electric.py in activity_histogram(self, period, bin_duration, **kwargs)
    687         # Calculate histogram...
    688         hist = np.zeros(n_bins, dtype=int)
--> 689         for on_chunk in when_on:
    690             if len(on_chunk) < 5:
    691                 continue

~/nilmtk/nilmtk/electric.py in when_on(self, on_power_threshold, **load_kwargs)
     51         """
     52         if on_power_threshold is None:
---> 53             on_power_threshold = self.on_power_threshold()
     54         for chunk in self.power_series(**load_kwargs):
     55             yield chunk >= on_power_threshold

~/nilmtk/nilmtk/electric.py in on_power_threshold(self)
     61         if not self.appliances:
     62             return DEFAULT_ON_POWER_THRESHOLD
---> 63         on_power_thresholds = [a.on_power_threshold() for a in self.appliances]
     64         return min(on_power_thresholds)
     65 

~/nilmtk/nilmtk/electric.py in <listcomp>(.0)
     61         if not self.appliances:
     62             return DEFAULT_ON_POWER_THRESHOLD
---> 63         on_power_thresholds = [a.on_power_threshold() for a in self.appliances]
     64         return min(on_power_thresholds)
     65 

~/nilmtk/nilmtk/appliance.py in on_power_threshold(self)
     66 
     67         try:
---> 68             return self.metadata['nominal_consumption']['on_power']
     69         except KeyError:
     70             threshold_from_appliance_type = self.type.get(

TypeError: 'int' object is not subscriptable
```

**Comment by PMeira** [comment] 2019-07-03 03:42
It should be fixed (and slightly improved) in the master branch. Tested with a couple of datasets. 
The GREEND issue was due to an error in the dataset.

**Closed by PMeira** 2019-07-03 03:42 UTC
Labels: bug
