### ISSUE TITLE
AssertionError caused by Plot() function in NILMTK

### ISSUE THREAD

**Issue by manojm18** [nilmtk/nilmtk#535] opened 2016-12-19 22:33 UTC
@nipunbatra @JackKelly
 I am trying to learn disaggregation. Every thing seemed to work (Loading data into memory, meter selection and basic statistics....etc ) but there seems to be a problem plotting the data in "Disaggregation and Metrics" part. After loading the data the plot function seems to throw an error. (Assertion Error)
Any idea how to fix this or what might be causing this error ??
```python
redd_train = DataSet('redd.h5')
building = 1
redd_train.buildings[building].elec.mains().plot()

<matplotlib.figure.Figure at 0xd8593c8>
Traceback (most recent call last):

  File "<ipython-input-5-0c81e0c351d3>", line 20, in <module>
    redd_train.buildings[building].elec.mains().plot()

  File "c:\users\manoj\nilmtk\nilmtk\metergroup.py", line 1371, in plot
    ax = function_map[kind](**kwargs)

  File "c:\users\manoj\nilmtk\nilmtk\metergroup.py", line 1382, in _plot_separate_lines
    ax = meter.plot(ax=ax, plot_legend=False, **kwargs)

  File "c:\users\manoj\nilmtk\nilmtk\electric.py", line 181, in plot
    power_series = self.power_series_all_data(**kwargs)

  File "c:\users\manoj\nilmtk\nilmtk\electric.py", line 107, in power_series_all_data
    for series in self.power_series(**kwargs):

  File "c:\users\manoj\nilmtk\nilmtk\electric.py", line 629, in load_series
    for chunk in generator:

  File "c:\users\manoj\nilmtk\nilmtk\preprocessing\apply.py", line 14, in process
    for chunk in self.upstream.process():

  File "c:\users\manoj\nilmtk\nilmtk\datastore\hdfdatastore.py", line 82, in load
    coords = self.store.select_as_coordinates(key=key, where=terms)

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 740, in select_as_coordinates
    stop=stop, **kwargs)

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3644, in read_coordinates
    coords = self.selection.select_coords()

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 4706, in select_coords
    sort=True)

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\tables\table.py", line 1606, in get_where_list
    self._where(condition, condvars, start, stop, step)]

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\tables\table.py", line 1506, in _where
    self, compiled, condition, condvars, start, stop, step)

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\tables\table.py", line 207, in _table__where_indexed
    range_ = index.get_lookup_range(ops, lims)

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\tables\index.py", line 2108, in get_lookup_range
    range_ = (lower, nextafter(upper, -1, coldtype, itemsize))

  File "C:\Users\Manoj\Anaconda2\lib\site-packages\tables\idxutils.py", line 474, in nextafter
    assert dtype.kind == "S" or type(x) in (bool, int, float)

AssertionError
```

**Comment by nipunbatra** [comment] 2016-12-20 07:13
PS the following guide to correct the bug report. That'll help us better to resolve your issue.

**Comment by manojm18** [comment] 2016-12-20 10:11
@nipunbatra @JackKelly
Apologies. I have updated my earlier report. Also the show_version prints out
```python
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
None

Date: 2016-12-20 11:06:11.452000
Platform: Windows-10-10.0.14393
System version: 2.7
nilmtk version: 0.2.0.dev-ef493f6
nilm_metadata version: 0.2.0.dev-2d0196c
numpy version: 1.11.2
matplotlib version: 1.5.3
pandas version: 0.19.1
sklearn version: 0.18.1
hmmlearn version: 0.1.1
```

**Comment by manojm18** [comment] 2016-12-23 21:35
@nipunbatra @JackKelly @oliparson 
Apologies. I have updated my earlier report. Also the show_version prints out.
```python
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
None

Date: 2016-12-20 11:06:11.452000
Platform: Windows-10-10.0.14393
System version: 2.7
nilmtk version: 0.2.0.dev-ef493f6
nilm_metadata version: 0.2.0.dev-2d0196c
numpy version: 1.11.2
matplotlib version: 1.5.3
pandas version: 0.19.1
sklearn version: 0.18.1
hmmlearn version: 0.1.1
```

**Comment by nipunbatra** [comment] 2016-12-24 08:40
Can you tell you the size of redd.h5 so created?

**Comment by manojm18** [comment] 2016-12-24 12:16
it is around 331MB

**Comment by manojm18** [comment] 2016-12-25 11:38
Hi,
I was wondering if the redd.h5 file could be corrupt. so i wanted to generate the h5 file from the low_freq data from redd data again.
surprisingly running the code below gave me a TypeError: shape must be an integer or sequence: 1L


```python
convert_redd('D:/DOCUMENTS/thesis/nilmtk-master/data/REDD/low_freq/low_freq', 'D:/DOCUMENTS/thesis/REDD/redd_gen.h5')

Loading house 1... 1 Traceback (most recent call last):

  File "<ipython-input-5-6cd3139b1a03>", line 1, in <module>
    convert_redd('D:/DOCUMENTS/thesis/nilmtk-master/data/REDD/low_freq/low_freq', 'D:/DOCUMENTS/thesis/REDD/redd_gen.h5')

  File "c:\users\manoj\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py", line 44, in convert_redd
    _convert(redd_path, store, _redd_measurement_mapping_func, 'US/Eastern')

  File "c:\users\manoj\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py", line 92, in _convert
    store.put(str(key), df)

  File "c:\users\manoj\nilmtk\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

  File "c:\users\manoj\nilmtk\nilmtk\datastore\hdfdatastore.py", line 160, in put
    expectedrows=len(value), index=False)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 873, in put
    self._write_to_group(key, value, append=append, **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 1315, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3853, in write
    **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3525, in create_axes
    raise e

TypeError: shape must be an integer or sequence: 1L```

I followed the same method to previously generate the redd.h5 file which ended up 331MB.

**Comment by nipunbatra** [comment] 2016-12-27 09:06
I am unable to reproduce this error on both OSX and Linux! The last time I checked on Windows, I didn't have any issues.

![screenshot_20161227_143400](https://cloud.githubusercontent.com/assets/60985/21496060/b70b3864-cc41-11e6-9654-02bd797d0853.png)

**Comment by manojm18** [comment] 2016-12-27 11:36
Hi Nipun,

Thank you for your response. maybe my h5 file is corrupt. also since i am facing error using convert_redd function, i would really appreciate if you could share the redd.h5 file through cloud sharing. so that i could check the codes in my machine with that file again.

Thank you.

**Comment by nipunbatra** [comment] 2016-12-29 11:54
PS the [iAWE H5](https://www.iiitd.edu.in/~nipunb/iawe/iawe.h5) file.

**Comment by nipunbatra** [comment] 2017-01-11 04:00
Can I close the issue now?

**Comment by manojm18** [comment] 2017-01-11 12:15
i still could not resolve the issue. hoping if someone else encounters a similar issue and finds a work around.

**Comment by nipunbatra** [comment] 2017-01-12 14:19
I tried nilmtk on Windows and can confirm this bug! 

```python
from nilmtk.dataset_converters import convert_redd
convert_redd('C:/Users/manojg/Downloads/low_freq/low_freq/', 'redd.h5')
```

```python
Loading house 1... 1 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d38c718ad871> in <module>()
----> 1 convert_redd('C:/Users/manojg/Downloads/low_freq/low_freq/', 'redd.h5')

c:\users\manojg\git\nilmtk\nilmtk\dataset_converters\redd\convert_redd.pyc in convert_redd(redd_path, output_filename, format)
     42 
     43     # Convert raw data to DataStore
---> 44     _convert(redd_path, store, _redd_measurement_mapping_func, 'US/Eastern')
     45 
     46     # Add metadata

c:\users\manojg\git\nilmtk\nilmtk\dataset_converters\redd\convert_redd.pyc in _convert(input_path, store, measurement_mapping_func, tz, sort_index)
     90             if sort_index:
     91                 df = df.sort_index() # raw REDD data isn't always sorted
---> 92             store.put(str(key), df)
     93         print()
     94 

c:\users\manojg\git\nilmtk\nilmtk\docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

c:\users\manojg\git\nilmtk\nilmtk\datastore\hdfdatastore.pyc in put(self, key, value)
    158     def put(self, key, value):
    159         self.store.put(key, value, format='table', 
--> 160                        expectedrows=len(value), index=False)
    161         self.store.create_table_index(key, columns=['index'], 
    162                                       kind='full', optlevel=9)

C:\Users\manojg\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in put(self, key, value, format, append, **kwargs)
    871             format = get_option("io.hdf.default_format") or 'fixed'
    872         kwargs = self._validate_format(format, kwargs)
--> 873         self._write_to_group(key, value, append=append, **kwargs)
    874 
    875     def remove(self, key, where=None, start=None, stop=None):

C:\Users\manojg\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1313 
   1314         # write the object
-> 1315         s.write(obj=value, append=append, complib=complib, **kwargs)
   1316 
   1317         if s.is_table and index:

C:\Users\manojg\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   3850         self.create_axes(axes=axes, obj=obj, validate=append,
   3851                          min_itemsize=min_itemsize,
-> 3852                          **kwargs)
   3853 
   3854         for a in self.axes:

C:\Users\manojg\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\io\pytables.pyc in create_axes(self, axes, obj, validate, nan_rep, data_columns, min_itemsize, **kwargs)
   3522                 self.values_axes.append(col)
   3523             except (NotImplementedError, ValueError, TypeError) as e:
-> 3524                 raise e
   3525             except Exception as detail:
   3526                 raise Exception(

TypeError: shape must be an integer or sequence: 1L
```

**Comment by nipunbatra** [comment] 2017-01-12 14:30
OK. I was able to get past this bug. Apparently, PyTables was causing this. I downgraded the version.

`conda install pytables==3.2.2` and now the above code works fine for me. Just pasting my `version` output.

```python
from nilmtk.utils import show_versions
show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
None

Date: 2017-01-12 19:51:27.566000
Platform: Windows-7-6.1.7601-SP1
System version: 2.7
nilmtk version: 0.2.0.dev-ef493f6
nilm_metadata version: 0.2.0.dev-2d0196c
numpy version: 1.11.3
matplotlib version: 1.5.3
pandas version: 0.19.2
sklearn version: 0.18.1
hmmlearn version: 0.1.1
```

**Closed by nipunbatra** 2017-01-12 14:30 UTC
