### ISSUE TITLE
UnicodeDecodeError when loading metadata

### ISSUE THREAD

**Issue by nilmtkhelp** [nilmtk/nilmtk#670] opened 2018-05-15 02:46 UTC
when I convert REDD data to ~.h5, I meet this below error.

help me!
```
from nilmtk.dataset_converters import convert_redd
convert_redd("C:\\Users\\Administrator\\REDD\\low_freq\\low_freq","C:\\Users\\Administrator\\REDD\\low_freq\\low_freq\\redd.h5")

Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 2... 1 2 3 4 5 6 7 8 9 10 11 
Loading house 3... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
Loading house 4... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 5... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 
Loaded metadata
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-128966c30980> in <module>()
      1 from nilmtk.dataset_converters import convert_redd
----> 2 convert_redd("C:\\Users\\Administrator\\REDD\\low_freq\\low_freq","C:\\Users\\Administrator\\REDD\\low_freq\\low_freq\\redd.h5")
      3 #convert_redd("I:\\전력 데이터\\REDD\\low_freq\\low_frequ","I:\\전력 데이터\\REDD\\low_freq\\redd.h5")

c:\users\administrator\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py in convert_redd(redd_path, output_filename, format)
     55                               'redd',
     56                               'metadata'),
---> 57                          store)
     58     store.close()
     59 

c:\users\administrator\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py in save_yaml_to_datastore(yaml_dir, store)
     77     metadata = _load_file(yaml_dir, 'dataset.yaml')
     78     print("Loaded metadata")
---> 79     meter_devices = _load_file(yaml_dir, 'meter_devices.yaml')
     80     metadata['meter_devices'] = meter_devices
     81     store.save_metadata('/', metadata)

c:\users\administrator\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py in _load_file(yaml_dir, yaml_filename)
    104     if isfile(yaml_full_filename):
    105         with open(yaml_full_filename) as fh:
--> 106             return yaml.load(fh)
    107     else:
    108         print(yaml_full_filename, "not found.", file=stderr)

~\Anaconda3\lib\site-packages\yaml\__init__.py in load(stream, Loader)
     68     and produce the corresponding Python object.
     69     """
---> 70     loader = Loader(stream)
     71     try:
     72         return loader.get_single_data()

~\Anaconda3\lib\site-packages\yaml\loader.py in __init__(self, stream)
     32 
     33     def __init__(self, stream):
---> 34         Reader.__init__(self, stream)
     35         Scanner.__init__(self)
     36         Parser.__init__(self)

~\Anaconda3\lib\site-packages\yaml\reader.py in __init__(self, stream)
     83             self.eof = False
     84             self.raw_buffer = None
---> 85             self.determine_encoding()
     86 
     87     def peek(self, index=0):

~\Anaconda3\lib\site-packages\yaml\reader.py in determine_encoding(self)
    122     def determine_encoding(self):
    123         while not self.eof and (self.raw_buffer is None or len(self.raw_buffer) < 2):
--> 124             self.update_raw()
    125         if isinstance(self.raw_buffer, bytes):
    126             if self.raw_buffer.startswith(codecs.BOM_UTF16_LE):

~\Anaconda3\lib\site-packages\yaml\reader.py in update_raw(self, size)
    176 
    177     def update_raw(self, size=4096):
--> 178         data = self.stream.read(size)
    179         if self.raw_buffer is None:
    180             self.raw_buffer = data

UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1591: illegal multibyte sequence
```

(**EDIT BY @PMeira**: Formatting)

**Comment by nipunbatra** [comment] 2018-05-20 14:18
@nilmtkhelp This seems like a Python 3 encoding issue to me.

https://stackoverflow.com/a/20994462/743775

Pinging @PMeira

**Comment by PMeira** [comment] 2018-05-21 13:44
It is some encoding issue but, since I cannot reproduce, I can't really help without more details.

The error itself happens inside pyyaml. For some reason it decides the encoding is cp949. @nilmtkhelp Did you edit the metadata files? If you didn't, we can force the converter to use UTF8 and bypass the automatic encoding detection issues.

**Comment by PMeira** [comment] 2018-05-21 13:58
@nilmtkhelp You could try to adding these lines before importing the any other module to see if it helps:
```python
import locale
locale.setlocale(locale.LC_ALL, 'en-US')
```

It's probably using the default encoding on nilm_metadata. I'll try to find a way to reproduce it, I probably need to install a language pack on Windows and set it as default to get the same error.

**Comment by PMeira** [comment] 2018-06-25 16:39
I'm closing this since there was no feedback and there is a potential workaround. If there is further development on this, please feel free to reopen.

The root cause can probably be fixed by changing how the YAML files are loaded in `nilm_metadata`. I won't make a PR right now since it's a very specific corner case.

Currently in `file_management.py`:
```python
        with open(filename) as fh:
            objs = yaml.load(fh)
```

Currently in `convert_yaml_to_hdf5.py`:
```python
        with open(yaml_full_filename) as fh:
            return yaml.load(fh)
```

Based on [PyYAML's documentation](http://pyyaml.org/wiki/PyYAMLDocumentation):
> A byte string or a file must be encoded with utf-8, utf-16-be or utf-16-le encoding. yaml.load detects the encoding by checking the BOM (byte order mark) sequence at the beginning of the string/file. If no BOM is present, the utf-8 encoding is assumed.

So, to avoid the "random" (locale dependent) encoding, loading the files as binary would use UTF-8 by default.

Proposed in `file_management.py`:
```python
        with open(filename, 'rb') as fh:
            objs = yaml.load(fh)
```

Proposed in `convert_yaml_to_hdf5.py`:
```python
        with open(yaml_full_filename, 'rb') as fh:
            return yaml.load(fh)
```

**Comment by Henry-Hero** [comment] 2019-06-05 05:07
I still get this error by installing nilmtk(user version) following install_user.md. But I solved it by adjusting code follow this guide. Hope some changes will make in user-version so that i don't need to do extra work after installation.

**Comment by PMeira** [comment] 2019-06-05 13:58
@Henry-Hero Thanks for letting us know, I'll reopen the issue since the PR hasn't been included yet.

**Comment by rajatgupta1234** [comment] 2019-06-18 05:09
@nilmtkhelp  @Henry-Hero 
![1](https://user-images.githubusercontent.com/46721220/59654751-3d982500-91b5-11e9-88ae-38cfa5a0d1ab.PNG)
Installing nilmtk with 
`conda install -c nilmtk nilmtk`  doesn't give any error while using the converter.

**Closed** 2019-06-19 03:04 UTC
Labels: needs more info

**Comment by PMeira** [comment] 2019-06-25 12:12
To clarify, the issue here is due to a OS setting which causes the default encoding to change to a unexpected value. The issue would be fixed in the current nilm_metadata master branch.

**Comment by Lewous** [comment] 2021-01-20 15:18
This happens when using the cloned nilm_metadata package instead of the released version. So, replace the nilm_metadata files will help.
