### ISSUE TITLE
How can I get the good sections data of one ElecMeter object?

### ISSUE THREAD

**Issue by hainan89** [nilmtk/nilmtk#711] opened 2018-10-29 12:57 UTC
Hi all,

I am trying to obtain the good sections data of one ElecMeter object. My codes are as follows:
<pre><code>
# load the REDD dataset
data = DataSet('./REDD/redd_low_freq.h5')

# then try to get the fridge meter data in building 1
building = 1
meter_fridge = data.buildings[building].elec[5]

# then I get a nilmtk.timeframegroup.TimeFrameGroup object
sections = meter_fridge.good_sections()
</pre></code>
However when I use the set_window function like this:
<pre><code>
data_sections = []
for one in meter_fridge.good_sections():
    one_sec = data.set_window(start=one.start, end=one.end)
</pre></code>
I got following errors:

<pre><code>
**TypeError: Cannot localize tz-aware Timestamp, use tz_convert for conversions.**

**The traceback states are as follows:**

Traceback (most recent call last):

  File "<ipython-input-12-70ea4a847da5>", line 4, in <module>
    end=one.end)

  File "d:\nilm\nilmtk-master\nilmtk\dataset.py", line 88, in set_window
    self.store.window = TimeFrame(start, end, tz)

  File "d:\nilm\nilmtk-master\nilmtk\timeframe.py", line 41, in __init__
    self._start = self._start.tz_localize(tz)

  File "pandas/_libs/tslibs/timestamps.pyx", line 912, in pandas._libs.tslibs.timestamps.Timestamp.tz_localize

**TypeError: Cannot localize tz-aware Timestamp, use tz_convert for conversions**
</pre></code>

Could anyone give me a clue? Thanks a lot.

**Comment by PMeira** [comment] 2018-11-25 22:33
Looks like another case of using the wrong Pandas version. Since it's been a while and I cannot reproduce it with the information listed here, I'm closing it. Feel free to reopen if more information (for example, a full code sample) is available.

**Closed by PMeira** 2018-11-25 22:33 UTC
