### ISSUE TITLE
Timestamp subtraction problems

### ISSUE THREAD

**Issue by MingjunZhong** [nilmtk/nilmtk#342] opened 2015-01-28 11:55 UTC
I have the following problems (see the code at the end of this post):

```python
runfile('/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py', wdir='/home/mzhong/2015-ideal/nilmtk-afhmmsac')
UMD has deleted: nilmtk.stats.totalenergy, nilmtk.timeframegroup, nilmtk.datastore.datastore, nilmtk, nilmtk.preprocessing, nilmtk.stats.dropoutrate, nilmtk.stats, nilmtk.docinherit, nilmtk.disaggregate.fhmm_exact, nilmtk.node, nilmtk.disaggregate.combinatorial_optimisation, nilmtk.stats.dropoutrateresults, nilmtk.elecmeter, nilmtk.version, nilmtk.consts, nilm_metadata.version, nilm_metadata.object_concatenation, nilmtk.disaggregate.hart_85, nilmtk.datastore.hdfdatastore, nilm_metadata, nilm_metadata.convert_yaml_to_hdf5, nilmtk.measurement, nilmtk.stats.totalenergyresults, nilmtk.plots, nilmtk.building, nilmtk.stats.goodsections, nilmtk.feature_detectors, nilmtk.feature_detectors.cluster, nilmtk.datastore.csvdatastore, nilmtk.datastore, nilmtk.preprocessing.clip, nilmtk.timeframe, nilmtk.stats.goodsectionsresults, nilmtk.utils, nilmtk.feature_detectors.steady_states, nilmtk.hashable, nilmtk.stats.histogram, nilmtk.dataset, nilm_metadata.file_management, nilmtk.datastore.key, nilmtk.preprocessing.apply, nilmtk.electric, nilmtk.exceptions, nilmtk.metergroup, nilmtk.disaggregate, nilmtk.results, nilmtk.appliance
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=12, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=13, building=1, dataset='REDD', appliances=[Appliance(type='electric space heater', instance=1)])'
Training model for submeter 'ElecMeter(instance=14, building=1, dataset='REDD', appliances=[Appliance(type='electric stove', instance=1)])'
Training model for submeter 'ElecMeter(instance=15, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=3)])'
Training model for submeter 'ElecMeter(instance=16, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=4)])'
Training model for submeter 'ElecMeter(instance=17, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=2)])'
Training model for submeter 'ElecMeter(instance=18, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=3)])'
Training model for submeter 'ElecMeter(instance=19, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=2)])'
Training model for submeter 'MeterGroup(meters=
  ElecMeter(instance=3, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
  ElecMeter(instance=4, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
)'
/home/mzhong/nilmtk/nilmtk/nilmtk/timeframe.py:246: UserWarning: Using a pytz._FixedOffset timezone may cause issues (e.g. might cause Pandas to raise 'TypeError: too many timezones in this block, create separate data columns').  It is better to set the timezone to a geographical location e.g. 'Europe/London'.
  warn("Using a pytz._FixedOffset timezone may cause issues"
/home/mzhong/nilmtk/nilmtk/nilmtk/electric.py:96: UserWarning: If you are using `preprocessing` to resample then please do not!  Instead, please use the `sample_period` parameter and set `resample=True`.
  warn("If you are using `preprocessing` to resample then please"
Traceback (most recent call last):

  File "<ipython-input-2-19d33dc62593>", line 1, in <module>
    runfile('/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py', wdir='/home/mzhong/2015-ideal/nilmtk-afhmmsac')

  File "/home/mzhong/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py", line 57, in <module>
    co.train(elec)

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.py", line 59, in train
    for chunk in meter.power_series(preprocessing=[Clip()]):

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/electric.py", line 587, in load_series
    for chunk in generator:

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/metergroup.py", line 663, in load
    for section in split_timeframes(sections, duration_threshold):

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/timeframe.py", line 293, in split_timeframes
    for split in timeframe.split(duration_threshold):

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/timeframe.py", line 274, in split
    if duration_threshold >= self.timedelta.total_seconds():

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/timeframe.py", line 128, in timedelta
    return self.end - self.start

  File "pandas/tslib.pyx", line 913, in pandas.tslib._Timestamp.__sub__ (pandas/tslib.c:17178)

TypeError: Timestamp subtraction must have the same timezones or no timezones
```

=============================================================================
The problems were posed after running the following code:

```python
from nilmtk import DataSet, TimeFrame
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.disaggregate import FHMM

target_file = '/home/mzhong/2015-ideal/energy-data/REDD/redd.h5'
redd = DataSet(target_file)

redd.store.window = TimeFrame(start=None, end='2011-05-01 00:00:00-04:00')

elec = redd.buildings[1].elec

co = CombinatorialOptimisation()
co.train(elec)
```

**Comment by JackKelly** [comment] 2015-01-28 13:18
in your code, please replace `redd.store.window = TimeFrame(start=None, end='2011-05-01 00:00:00-04:00')` with `redd.set_window(start=None, end='2011-05-01 00:00:00')`.

The issue is that the timezone is set to `US/Eastern` and Pandas doesn't understand that `US/Eastern` is kind of the same as `-04:00`.  The `dataset.set_window` method takes care of the timezone for you ;)

I'll close this issue for now because this fixes the issue for me.  Please re-open if this does not fix the issue for you ;)

**Closed by JackKelly** 2015-01-28 13:18 UTC

**Comment by MingjunZhong** [comment] 2015-01-28 13:39
Thanks, it solved the problem

**Comment by nipunreddevil** [comment] 2015-01-28 16:21
@JackKelly Glad you implemented the newer way of using the timezone. Else, DST changes would have really messed up things!

I think this issue cropped up because we have not yet updated some of the IPython notebooks.

Thanks for reporting @MingjunZhong .
