### ISSUE TITLE
cannot reshape array of size ...  with ECO dataset 

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#775] opened 2019-05-31 15:07 UTC
I am trying to test the disaggregation features of the ECO dataset, and I am facing some problems with the prediction. When I run this piece of code, I get the following error:

```
for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
```

Can anyone help to sort out this error? I have no idea why this is happening.

**Comment by nipunbatra** [comment] 2019-05-31 15:15
@raktim2015: This seems like duplicate of a previous issue where the power column was not being mentioned. Could you please make changes to: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb 
and also reply to this thread.

**Comment by raktim2015** [comment] 2019-05-31 15:21
Actually Ayush Bhaiya is taking care of ECO dataset. I am telling him to
look into the issue.
Please merge my previous pull request of download_dataport.py.  I have
almost completed making the DRED converter !! I will be able to pull a
request soon.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/31/19,
8:50:26 PM

**Comment by nipunbatra** [comment] 2019-05-31 15:29
@nekovolta This seems like a duplicate of: https://github.com/nilmtk/nilmtk/issues/750
@raktim2015: Please the pertinent update from #750 into the disaggregation and metrics notebook where we mention that we can load a specific `ac_type` and `physical_quantity`.

**Comment by nekovolta** [comment] 2019-06-03 10:27
I guess the NILMTK has been updated. I just installed it following these instructions:

[https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md](url)

Is there any instructions (or similar) to check how to update the NILMTK environment?

**Comment by ayushp20** [comment] 2019-06-04 09:58
@nekovolta, For now, the best practice is to install NILMTK in a separate environment. It is better to stick to the versions of the dependencies that are installed. We are working on upgrading them to their newer versions.

**Comment by nekovolta** [comment] 2019-06-04 13:50
I follow the indications in #750 and I understood and solved the problem. I selected the powerto make it one-dimensional. So, replacing this piece of code worked perfectly:

pred = {}
gt= {}
  
```
for i, chunk in enumerate(test_elec.mains().load(physical_quantity='power',ac_type='active',sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
```

However, I still can not finish the implementation. I added and updated the next lines as follows, to take only into account only the power readings:


    
```
    for meter in test_elec.submeters().meters:
        gt[i][meter] = next(meter.load(physical_quantity='power',ac_type='active',sample_period=60))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna() 
```

The problem is that now it appears this error: 

![image](https://user-images.githubusercontent.com/29656053/58884330-7974ba00-86e0-11e9-9e6f-4bb07f90cb1e.png)

How can I solve it?

**Comment by ayushp20** [comment] 2019-06-04 14:02
We check whether the value of the key-value is not 0, and only then proceed with adding it to the dataframe.
Use this code. 
```python
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i]) if len(v) }, index=next(iter(gt[i].values())).index).dropna()
```
Will push these changes to the conda package soon.

**Comment by nekovolta** [comment] 2019-06-04 14:52
I tried with that code, and it works now. The problem now is that after that loop, I have an error in the next lines:

```
gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

gt_overall = gt_overall[pred_overall.columns]
```

The problem is with the last line. The error is the next one:

![image](https://user-images.githubusercontent.com/29656053/58889425-2bb07f80-86e9-11e9-95d5-02f8fbffd022.png)

**Comment by nekovolta** [comment] 2019-06-05 10:58
I reckon that this error should be related to the fact that I am using the _five top-consumption appliances_, but this procedure was done the same way with the example for REDD dataset without issues:

[https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb](url)

I tried with **one appliance** making **k=1** in these lines, that implies selecting the appliance with high consumption, which is the **fridge**.

```
top_5_train_elec = train_elec.submeters().select_top_k(k=1)
top_5_train_elec
```

I tried this way, and I did not have the issues commented previously.

**Comment by ayushp20** [comment] 2019-06-05 20:20
I am unable to replicate your "KeyError: "Index....not in index".
I ran the entire notebook with all the appliances (not just top 5) without any errors and a reasonably good benchmarking prediction. I did use a higher sampling rate because of the slow training, though that shouldn't be a problem as long as you let the notebook run completely.
```python
start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=600)
end = time.time()
print("Runtime =", end-start, "seconds.")
pred = {}
gt= {}
sample_period=600
for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    for meter in test_elec.submeters().meters:
        gt[i][meter] = next(meter.load(physical_quantity = 'power',ac_type = 'active', sample_period=sample_period))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i]) if len(v)}, index=next(iter(gt[i].values())).index).dropna()
# If everything can fit in memory
gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]

#Intersection of index
gt_index_utc = gt_overall.index.tz_convert("UTC")
pred_index_utc = pred_overall.index.tz_convert("UTC")
common_index_utc = gt_index_utc.intersection(pred_index_utc)
local_timezone = train.metadata['timezone']
common_index_local = common_index_utc.tz_convert(local_timezone)
gt_overall = gt_overall.ix[common_index_local]
pred_overall = pred_overall.ix[common_index_local]
appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels
pred_overall.columns = appliance_labels
pred_overall['Fridge'].head(100).plot(label="Pred")
gt_overall['Fridge'].head(100).plot(label="GT")
plt.legend()
```
![image](https://user-images.githubusercontent.com/36565028/58987578-49581480-87cf-11e9-9ca4-4f9a79feec3e.png)

NB - It is better to paste the errors in markdown too for better indexing.

**Comment by ayushp20** [comment] 2019-06-05 21:07
This error does show up when I run disaggregation over the entire timeframe, and is specifically related to the 'computer'.
```python
KeyError: "[ElecMeter(instance=9, building=1, dataset='ECO', appliances=[Appliance(type='computer', instance=1)])] not in index"
```
This happens because the ground truth does not have the 'computer' column, while the classifier predicts a computer. Computer in gt must have been dropped due to empty values. It was fixed by removing the code that sets same order of the labels and letting gt_overall and pred_overall have separate labels:
```python
# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]  #remove
appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels
gt_overall.head()
appliance_labels2 = [m.label() for m in pred_overall.columns.values]
pred_overall.columns = appliance_labels2
pred_overall.head()
```
The order of the labels does get compromised, but the rest is fine for now.

**Comment by nekovolta** [comment] 2019-06-10 12:10
@ayushp20 the piece of code you proposed:

```python
# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]  #remove
appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels
gt_overall.head()
appliance_labels2 = [m.label() for m in pred_overall.columns.values]
pred_overall.columns = appliance_labels2
pred_overall.head()
```

Should replace this piece of code **maintaining the rest of the code**?

```python
# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]

#Intersection of index
gt_index_utc = gt_overall.index.tz_convert("UTC")
pred_index_utc = pred_overall.index.tz_convert("UTC")
common_index_utc = gt_index_utc.intersection(pred_index_utc)

local_timezone = train.metadata['timezone']

common_index_local = common_index_utc.tz_convert(local_timezone)

gt_overall = gt_overall.ix[common_index_local]
pred_overall = pred_overall.ix[common_index_local]

gt_overall.head()

# to use prettier labels for appliances
appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels
pred_overall.columns = appliance_labels

pred_overall.head()
```

I tried replacing that portion of code and **considering the entire timeframe**, but I got this error:


```python
Traceback (most recent call last):

  File "<ipython-input-190-9e7516921cda>", line 1, in <module>
    runfile('K:/Disaggregation_ECO_test_entiretimeframe.py', wdir='K:')

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "K:/Disaggregation_ECO_test_entiretimeframe.py", line 133, in <module>
    gt_overall['Fridge'].head(100).plot(label="GT")

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\plotting\_core.py", line 2503, in __call__
    **kwds)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\plotting\_core.py", line 1927, in plot_series
    **kwds)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\plotting\_core.py", line 1729, in _plot
    plot_obj.generate()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\plotting\_core.py", line 250, in generate
    self._compute_plot_data()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\plotting\_core.py", line 365, in _compute_plot_data
    'plot'.format(numeric_data.__class__.__name__))

TypeError: Empty 'DataFrame': no numeric data to plot
```

![image](https://user-images.githubusercontent.com/29656053/59194403-3788bf80-8b89-11e9-9eec-5f1363a6042e.png)

So it seems

**Comment by ayushp20** [comment] 2019-06-19 12:11
Again this problem is really specific to ECO dataset. With minimal code we can check that the appliance "Computer" doesn't exist somewhere after 15-08-2012.
```python
df1 = next(train_elec.select_using_appliances(type='hair dryer').load(sample_period = 600))
df2 = next(train_elec.select_using_appliances(type='computer').load(sample_period = 600))
df1['power']['active'].plot(label='hair dryer')
df2['power']['active'].plot(label='computer')
plt.legend()
```
![Screenshot from 2019-06-19 17-32-14](https://user-images.githubusercontent.com/36565028/59763984-4d356d80-928a-11e9-87cd-e516b9f9c354.png)

The test_elec.submeters() list this appliance but it is an empty value for this key. So this will create problems whenever we test beyond this timeframe.
```python
pred = {}
gt= {}
sample_period=600
for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    for meter in test_elec.submeters().meters:
        gt[i][meter] = next(meter.load(physical_quantity = 'power',ac_type = 'active', sample_period=sample_period))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i]) if len(v)!= 0}, index=next(iter(gt[i].values())).index).dropna()

gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

#Intersection of index
gt_index_utc = gt_overall.index.tz_convert("UTC")
pred_index_utc = pred_overall.index.tz_convert("UTC")
common_index_utc = gt_index_utc.intersection(pred_index_utc)
local_timezone = train.metadata['timezone']
common_index_local = common_index_utc.tz_convert(local_timezone)
gt_overall = gt_overall.ix[common_index_local]
pred_overall = pred_overall.ix[common_index_local]

appliance_labels2 = [m.label() for m in pred_overall.columns.values]
pred_overall.columns = appliance_labels2

appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels

#Code that drops the column in pred_overall not present in ground truth.
n = pred_overall.shape[1]
i=0
while i < n:
    #print(i)
    if  pred_overall.columns.values[i] not in gt_overall.columns.values:
        str = pred_overall.columns.values[i]
        pred_overall = pred_overall.drop(pred_overall.columns.values[i], axis = 1)
        print("Dropping "+str+" from dataframe.")
        n = pred_overall.shape[1]
    i+=1

pred_overall['Freezer'].head(100).plot(label="Pred")
gt_overall['Freezer'].head(100).plot(label="GT")
plt.legend()

from sklearn.metrics import mean_squared_error
rms_error = {}
for appliance in pred_overall.columns:
    rms_error[appliance] = np.sqrt(mean_squared_error(gt_overall[appliance], pred_overall[appliance]))
pd.Series(rms_error)
Fridge              28.216663
Hair dryer         188.547455
Kettle             238.854029
Washing machine    240.516339
Freezer             15.339937
dtype: float64
```
Tested and working on the entire dataset. Ground truth has 6 columns whereas predictions have only 5, all of which match.

**Closed** 2019-08-21 00:40 UTC
