### ISSUE TITLE
proportion_of_energy_submetered() raises an IndexError

### ISSUE THREAD

**Issue by jhyun0919** [nilmtk/nilmtk#471] opened 2016-01-18 01:12 UTC
Stats for MeterGroups
-----------------------------------------
Proportion of energy submetered

----------------------------------------------
```python
In [10]: elec.proportion_of_energy_submetered()

---------------------------------------------
Running MeterGroup.proportion_of_energy_submetered...
nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/tseries/base.py:100: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = getitem(key)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-3b14c6037fc4> in <module>()
----> 1 elec.proportion_of_energy_submetered()

/root/nilmtk/nilmtk/metergroup.pyc in proportion_of_energy_submetered(self, **loader_kwargs)
   1050             if verbose:
   1051                 print("Calculating proportion for", m)
-> 1052             prop = m.proportion_of_energy(mains, **loader_kwargs)
   1053             if not np.isnan(prop):
   1054                 proportion += prop

/root/nilmtk/nilmtk/electric.pyc in proportion_of_energy(self, other, **loader_kwargs)
    282         float [0,1] or NaN if other.total_energy == 0
    283         """
--> 284         good_other_sections = other.good_sections(**loader_kwargs)
    285         loader_kwargs.setdefault('sections', good_other_sections)
    286 

/root/nilmtk/nilmtk/metergroup.pyc in good_sections(self, **kwargs)
    903                      " return the intersection of the good sections for all"
    904                      " meters.  This will be fixed...")
--> 905             return self.meters[0].good_sections(**kwargs)
    906         else:
    907             return []

/root/nilmtk/nilmtk/elecmeter.pyc in good_sections(self, **loader_kwargs)
    630         results_obj = GoodSections.results_class(self.device['max_sample_period'])
    631         return self._get_stat_from_cache_or_compute(
--> 632             nodes, results_obj, loader_kwargs)        
    633 
    634     def _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs):

/root/nilmtk/nilmtk/elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    684         if loader_kwargs.get('preprocessing') is None:
    685             cached_stat = self.get_cached_stat(key_for_cached_stat)
--> 686             results_obj.import_from_cache(cached_stat, sections)
    687 
    688             def find_sections_to_compute():

/root/nilmtk/nilmtk/stats/goodsectionsresults.pyc in import_from_cache(self, cached_stat, sections)
    116                     timeframes = []
    117                     for _, row in sections_df.iterrows():
--> 118                         section_start = tz_localize_naive(row['section_start'], tz)
    119                         section_end = tz_localize_naive(row['section_end'], tz)
    120                         timeframes.append(TimeFrame(section_start, section_end))

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    555     def __getitem__(self, key):
    556         try:
--> 557             result = self.index.get_value(self, key)
    558 
    559             if not np.isscalar(result):

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/index.pyc in get_value(self, series, key)
   1778         s = getattr(series,'_values',None)
   1779         if isinstance(s, Index) and lib.isscalar(key):
-> 1780             return s[key]
   1781 
   1782         s = _values_from_object(series)

/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/tseries/base.pyc in __getitem__(self, key)
     98         getitem = self._data.__getitem__
     99         if np.isscalar(key):
--> 100             val = getitem(key)
    101             return self._box_func(val)
    102         else:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by nipunbatra** [comment] 2016-01-18 02:28
Please let us know how to reproduce this bug. 

PS: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/contributing.md

**Comment by jhyun0919** [comment] 2016-01-18 05:15
Following lines are how I've done to reproduce this bug.
===================================================

In [1]: from matplotlib import rcParams

In [2]: import matplotlib.pyplot as plt

In [3]: %matplotlib

(process:15842): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:15842): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python:15842): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Using matplotlib backend: Qt4Agg

In [4]: rcParams['figure.figsize'] = (13, 6)

In [5]: plt.style.use('ggplot')

In [6]: from nilmtk import DataSet

In [7]: redd = DataSet('/data/REDD/redd.h5')

In [8]: elec = redd.buildings[1].elec

In [9]: elec.proportion_of_energy_submetered()
Running MeterGroup.proportion_of_energy_submetered...
nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
/root/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/tseries/base.py:100: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = getitem(key)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
.
.
.
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by nipunbatra** [comment] 2016-01-18 05:31
I can't reproduce this 

```python
In [1]:  from nilmtk import DataSet
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 27 days

In [2]:  redd = DataSet('/data/REDD/redd.h5')

In [3]: elec = redd.buildings[1].elec

In [4]: elec.proportion_of_energy_submetered()
Running MeterGroup.proportion_of_energy_submetered...
/Users/nipunbatra/git/nilmtk/nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
Calculating total_energy for ElecMeterID(instance=2, building=1, dataset='REDD') ...   /Users/nipunbatra/git/nilmtk/nilmtk/electric.py:307: UserWarning: No shared AC types.  Using 'active' for submeter and 'apparent' for other.
  " and '{:s}' for other.".format(ac_type, other_ac_type))
Calculating total_energy for ElecMeterID(instance=2, building=1, dataset='REDD') ...   Out[4]: 0.75990318508883437
```

I suspect you have some library version issues.

```python

In [8]: from nilmtk.utils import show_versions

In [9]: show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.21
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.8.0.dev0+4017cab
IPython: 3.1.0
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
bottleneck: None
tables: 3.1.1
numexpr: 2.3.1
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.5.7
lxml: 3.4.0
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.2
pymysql: None
psycopg2: None
None

Date: 2016-01-18 11:01:01.947322
Platform: Darwin-15.0.0-x86_64-i386-64bit
System version: 2.7
nilmtk version: 0.2.0.dev-
nilm_metadata version: 0.2.0.dev-24d529f
numpy version: 1.10.1
matplotlib version: 1.4.3
pandas version: 0.16.2
sklearn version: 0.17
hmmlearn version: 0.1a

```

PS: Please see Github Markdown to format your comments :)

**Comment by JackKelly** [comment] 2016-01-18 08:38
@jhyun0919 as Nipun says, we need to see which software versions you are using.  Please can you do this and show us the result:

```python
In [8]: from nilmtk.utils import show_versions
In [9]: show_versions()
```

**Comment by jhyun0919** [comment] 2016-01-19 08:07
following lines are the result of my software environments.
```python
In [1]: from nilmtk.utils import show_versions

In [2]: show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 19.1.1
Cython: 0.23.4
numpy: 1.10.2
scipy: 0.16.1
statsmodels: None
IPython: 4.0.1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None
None

Date: 2016-01-18 17:37:24.526628
Platform: Linux-3.19.0-43-generic-x86_64-with-debian-jessie-sid
System version: 2.7
nilmtk version: 0.2.0.dev-b51d827
nilm_metadata version: 0.2.0.dev-336e30f
numpy version: 1.10.2
matplotlib version: 1.5.0
pandas version: 0.17.1
sklearn version: 0.17
hmmlearn version: 0.1.1

```

There are some differences between Nipun's and my lib version.
So I've worked on updating mine and following is updated result.

```python

In [7]: show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 7.1.2
setuptools: 19.1.1
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.1
sphinx: 1.2.2
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.5.0
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None
None

Date: 2016-01-18 19:19:06.518233
Platform: Linux-3.19.0-43-generic-x86_64-with-debian-jessie-sid
System version: 2.7
nilmtk version: 0.2.0.dev-b51d827
nilm_metadata version: 0.2.0.dev-336e30f
numpy version: 1.10.1
matplotlib version: 1.5.0
pandas version: 0.17.1
sklearn version: 0.17
hmmlearn version: 0.1.1
```

Though the Index Error did not disappear...
```python
In [17]: elec.proportion_of_energy_submetered()
Running MeterGroup.proportion_of_energy_submetered...
/root/nilmtk/nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
/root/anaconda2/lib/python2.7/site-packages/pandas/tseries/base.py:100: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = getitem(key)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-3b14c6037fc4> in <module>()
----> 1 elec.proportion_of_energy_submetered()

/root/nilmtk/nilmtk/metergroup.pyc in proportion_of_energy_submetered(self, **loader_kwargs)
   1050             if verbose:
   1051                 print("Calculating proportion for", m)
-> 1052             prop = m.proportion_of_energy(mains, **loader_kwargs)
   1053             if not np.isnan(prop):
   1054                 proportion += prop

/root/nilmtk/nilmtk/electric.pyc in proportion_of_energy(self, other, **loader_kwargs)
    282         float [0,1] or NaN if other.total_energy == 0
    283         """
--> 284         good_other_sections = other.good_sections(**loader_kwargs)
    285         loader_kwargs.setdefault('sections', good_other_sections)
    286 

/root/nilmtk/nilmtk/metergroup.pyc in good_sections(self, **kwargs)
    903                      " return the intersection of the good sections for all"
    904                      " meters.  This will be fixed...")
--> 905             return self.meters[0].good_sections(**kwargs)
    906         else:
    907             return []

/root/nilmtk/nilmtk/elecmeter.pyc in good_sections(self, **loader_kwargs)
    630         results_obj = GoodSections.results_class(self.device['max_sample_period'])
    631         return self._get_stat_from_cache_or_compute(
--> 632             nodes, results_obj, loader_kwargs)        
    633 
    634     def _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs):

/root/nilmtk/nilmtk/elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    684         if loader_kwargs.get('preprocessing') is None:
    685             cached_stat = self.get_cached_stat(key_for_cached_stat)
--> 686             results_obj.import_from_cache(cached_stat, sections)
    687 
    688             def find_sections_to_compute():

/root/nilmtk/nilmtk/stats/goodsectionsresults.pyc in import_from_cache(self, cached_stat, sections)
    116                     timeframes = []
    117                     for _, row in sections_df.iterrows():
--> 118                         section_start = tz_localize_naive(row['section_start'], tz)
    119                         section_end = tz_localize_naive(row['section_end'], tz)
    120                         timeframes.append(TimeFrame(section_start, section_end))

/root/anaconda2/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    555     def __getitem__(self, key):
    556         try:
--> 557             result = self.index.get_value(self, key)
    558 
    559             if not np.isscalar(result):

/root/anaconda2/lib/python2.7/site-packages/pandas/core/index.pyc in get_value(self, series, key)
   1778         s = getattr(series,'_values',None)
   1779         if isinstance(s, Index) and lib.isscalar(key):
-> 1780             return s[key]
   1781 
   1782         s = _values_from_object(series)

/root/anaconda2/lib/python2.7/site-packages/pandas/tseries/base.pyc in __getitem__(self, key)
     98         getitem = self._data.__getitem__
     99         if np.isscalar(key):
--> 100             val = getitem(key)
    101             return self._box_func(val)
    102         else:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by JackKelly** [comment] 2016-01-19 08:52
Hmm, I suspect there might be an issue with your `redd.h5` file.  Please can you tell us the exact size of your `redd.h5` file (on Linux you can use `ls -l redd.h5`), e.g.:

```shell
jack@probook:/data/REDD$ ls -l redd.h5
-rw-rw-r-- 1 jack jack 286601109 May  6  2015 redd.h5
```

Also, were there any errors during conversion?

**Comment by jhyun0919** [comment] 2016-01-19 09:05
Here is the result what you asked.
```linux
(nilmtk-env)root@ubuntu:/data/REDD# ls -l redd.h5 
-rw-r--r-- 1 jeehyunpark jeehyunpark 346598724 Jan 19 18:02 redd.h5
```

And there was no error during conversion REDD to HDF5
```python
In [1]: from nilmtk.utils import print_dict
/root/nilmtk/nilmtk/node.py:2: ImportWarning: Not importing directory 'nilm_metadata': missing __init__.py
  from nilm_metadata import recursively_update_dict

In [2]: from nilmtk.dataset_converters import convert_redd

In [3]: convert_redd('/data/REDD/low_freq', '/data/REDD/redd.h5')
Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 2... 1 2 3 4 5 6 7 8 9 10 11 
Loading house 3... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
Loading house 4... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 5... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 
Done converting YAML metadata to HDF5!
Done converting REDD to HDF5!
```

**Comment by JackKelly** [comment] 2016-01-19 09:11
Thanks.  OK.   The file sizes are rather different, which might suggest that something strange has happened with your `redd.h5` file: 

```
yours = 346,598,724 bytes
mine  = 286,601,109 bytes
```

@nipunbatra, how big is your `redd.h5` file?

@jhyun0919 I wonder if something odd has happened with the download of your REDD files.  Please can you show us the sizes of the directories in your REDD low_freq directory?  Something like this:

```shell
jack@probook:/data/REDD/low_freq$ du -h .
118M	./house_6
215M	./house_4
41M	./house_5
174M	./house_3
260M	./house_1
84M	./house_2
890M	.
```

**Comment by nipunbatra** [comment] 2016-01-19 09:15
Mine is `345324430` bytes. For some reason, I still think that this is a library version mismatch. Could you try downgrading pandas to 0.16.2?

**Comment by JackKelly** [comment] 2016-01-19 09:18
> Could you try downgrading pandas to 0.16.2?

Hmm... I've been using Pandas 0.17.1 for a while and it seems to work OK with NILMTK.  Let me see if I can recreate @jhyun0919's bug... give me a few minutes...

**Comment by JackKelly** [comment] 2016-01-19 09:20
OK, I can recreate this bug.  I'll work on fixing it now.  Sorry, I should've done this sooner...

**Comment by jhyun0919** [comment] 2016-01-19 09:20
@JackKelly There's no difference in REDD low_freq
```
root@ubuntu:/data/REDD/low_freq# du -h
41M	./house_5
118M	./house_6
174M	./house_3
215M	./house_4
84M	./house_2
260M	./house_1
890M	.

```

**Comment by JackKelly** [comment] 2016-01-19 10:05
I think we might have bumped into a bug in Pandas 0.17.1.  I have submitted an issue to the wonderful Pandas folks here: https://github.com/pydata/pandas/issues/12089

**Comment by JackKelly** [comment] 2016-01-19 10:10
@jhyun0919 as Nipun says, if you want a quick solution then try down-grading to Pandas 0.16.2.  Or, if you want to help diagnose the issue, it might be useful to see if this bug exists in Pandas 0.17.0 (although there is [a separate bug in 0.17.0 which affects NILMTK](https://github.com/nilmtk/nilmtk/issues/456) so only use 0.17.0 if you're happy to invest a little time exploring if the current `IndexError` bug exists in 0.17.0)).

**Comment by jhyun0919** [comment] 2016-01-21 09:34
At first, it seems like downgrading pandas solved the problem.
But another type of error occurred.

Following is the result...


```python
In [9]: elec.proportion_of_energy_submetered()
Running MeterGroup.proportion_of_energy_submetered...
/root/nilmtk/nilmtk/metergroup.py:901: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
Calculating total_energy for ElecMeterID(instance=2, building=1, dataset='REDD') ...   /root/nilmtk/nilmtk/electric.py:307: UserWarning: No shared AC types.  Using 'active' for submeter and 'apparent' for other.
  " and '{:s}' for other.".format(ac_type, other_ac_type))
Calculating total_energy for ElecMeterID(instance=2, building=1, dataset='REDD') ...   ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-3b14c6037fc4> in <module>()
----> 1 elec.proportion_of_energy_submetered()

/root/nilmtk/nilmtk/metergroup.pyc in proportion_of_energy_submetered(self, **loader_kwargs)
   1050             if verbose:
   1051                 print("Calculating proportion for", m)
-> 1052             prop = m.proportion_of_energy(mains, **loader_kwargs)
   1053             if not np.isnan(prop):
   1054                 proportion += prop

/root/nilmtk/nilmtk/electric.pyc in proportion_of_energy(self, other, **loader_kwargs)
    290             return np.NaN
    291 
--> 292         total_energy = self.total_energy(**loader_kwargs)
    293         if total_energy.empty:
    294             return 0.0

/root/nilmtk/nilmtk/elecmeter.pyc in total_energy(self, **loader_kwargs)
    591         nodes = [Clip, TotalEnergy]
    592         return self._get_stat_from_cache_or_compute(
--> 593             nodes, TotalEnergy.results_class(), loader_kwargs)
    594 
    595     def dropout_rate(self, ignore_gaps=True, **loader_kwargs):

/root/nilmtk/nilmtk/elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    684         if loader_kwargs.get('preprocessing') is None:
    685             cached_stat = self.get_cached_stat(key_for_cached_stat)
--> 686             results_obj.import_from_cache(cached_stat, sections)
    687 
    688             def find_sections_to_compute():

/root/nilmtk/nilmtk/results.pyc in import_from_cache(self, cached_stat, sections)
    161             else:
    162                 if isinstance(rows_matching_start, pd.Series):
--> 163                     append_row(rows_matching_start, section)
    164                 else:
    165                     for row_i in range(rows_matching_start.shape[0]):

/root/nilmtk/nilmtk/results.pyc in append_row(row, section)
    148             # so now we must put the timezone back.
    149             row['end'] = tz_localize_naive(row['end'], tz)
--> 150             if row['end'] == section.end:
    151                 usable_sections_from_cache.append(row)
    152 

pandas/tslib.pyx in pandas.tslib._Timestamp.__richcmp__ (pandas/tslib.c:16186)()

pandas/tslib.pyx in pandas.tslib._Timestamp._assert_tzawareness_compat (pandas/tslib.c:16566)()

TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by nipunbatra** [comment] 2016-01-21 09:37
Oh no! Sorry that you're having all this trouble! I'd suggest that to you move to other functionality of niltmtk in the meanwhile. This is also a Pandas issue that got resolved in some version! I think it'd be best to use other core nilmtk functionality and then move to Pandas master once the originial bug gets closed by the Pandas team! Thanks for hanging on! But, even we can't do much! Just to keep your spirits up, the function that you're using is seldom used by me. I mostly use the core nilmtk functionality.

**Comment by JackKelly** [comment] 2016-01-21 10:21
@jhyun0919 which version of Pandas did you install?

**Comment by jhyun0919** [comment] 2016-01-21 10:37
pandas: 0.16.2

```python
In [10]: from nilmtk.utils import show_versions

In [11]: show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
```

**Comment by JackKelly** [comment] 2016-01-27 13:06
the wonderful @jreback [has just fixed](https://github.com/pydata/pandas/commit/3152bdca818f44351ca1c8b63cb26fcfeae3cce7) the [Pandas bug](https://github.com/pydata/pandas/issues/12089).  So, @jhyun0919 (and other NILMTK users): if you pull the latest version of Pandas from git then this bug should be fixed.  I'll close this NILMTK issue for now.

**Closed by JackKelly** 2016-01-27 13:06 UTC
