### ISSUE TITLE
Issues on Pycharm 

### ISSUE THREAD

**Issue by salmanshahid8** [nilmtk/nilmtk#720] opened 2018-12-12 10:19 UTC
Hi, 
So here are the issues I faced on Pycharm so forth. I am working on REFIT dataset as it has same attributes to that of IRISE dataset that I will use later.

1) Issue #717 . Rather then using a new environment in pycharm, I upgraged/downgraded all the necessary packages and installed the git packages. Now I am using the default anaconda environment which is fulfilling all the dependencies.

2) When I give this commands fridge.available_columns() for the building 7, the IDE generates an "Exception: search terms match 2 appliances", although there is only one fridge in the building, however there are 2 freezers in the same building. This exception should only happen in building 1 where there are 2 fridges.

3) .plot() function does not work. similarly, .draw_wiring_graph() is not working either. Why so?

Any ideas how to fix that.

**Comment by PMeira** [comment] 2018-12-14 16:38
@salmanshahid8 I'd try either reinstalling everything from scratch (your conda install seems to have some issues) or installing in a VM to be evaluate if the issue is in NILMTK or your environment. I can't help much on the Pycharm aspect itself since I don't use it.

**Comment by salmanshahid8** [comment] 2019-02-01 15:34
@PMeira Is there any new version of NILMTK to be made public soon?
btw your NILMTK package helped much better then the repository. thanks for that.

**Comment by PMeira** [comment] 2019-02-04 18:08
@salmanshahid8 I started fixing the issues with Pandas 0.24 but probably won't finish that in the next week or so. I do expect at least a proper beta release by the end of the month.

Sorry for the delay, I was expecting Pandas 0.24 before the end of 2018 but it was released only in January. I did manage to get a fix for a bug I found before the release though, so that's a positive: https://github.com/pandas-dev/pandas/issues/24805

As soon as I get most of it working, I'll release another conda package.

**Comment by PMeira** [comment] 2019-06-23 16:39
Closing since most of the Pandas issues should be fixed.

Re-reading now, for future reference:

> "Exception: search terms match 2 appliances", although there is only one fridge in the building, however there are 2 freezers in the same building. This exception should only happen in building 1 where there are 2 fridges.

Fridges and freezers are classified in the same category in the metadata and are considered synonyms, hence why it matches multiple appliances. Setting `nilmtk.Appliance.allow_synonyms = False` should be enough to keep them separate.

> .plot() function does not work. similarly, .draw_wiring_graph() is not working either. Why so?

This was probably due to the something in Pycharm installation, we haven't got any similar report so far.

**Closed by PMeira** 2019-06-23 16:39 UTC
Labels: Installation, support
