### ISSUE TITLE
Hart85 issue

### ISSUE THREAD

**Issue by omegawea** [nilmtk/nilmtk#674] opened 2018-06-11 20:14 UTC
I am working with my own dataset and trying to verify the disaggregation with active and reactive power ussing hart85.

However, it shows TypeError: data type not understood. Here is my code:
```python
from nilmtk.disaggregate import hart_85
hart = hart_85.Hart85()
hart.train(top_3_train_elec, sample_period=chooseSample, cols=[('power', 'active'), ('power', 'reactive')])
```
And here is my error:
```pytb
Loading data for meter ElecMeterID(instance=2, building=1, dataset='XXX')      
Done loading data all meters for this chunk.
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-3a561f2ff917> in <module>()
      1 hart = hart_85.Hart85()
----> 2 hart.train(top_3_train_elec, sample_period=chooseSample, cols=[('power', 'active'), ('power', 'reactive')])

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in train(self, metergroup, cols, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    240             metergroup, cols, noise_level, state_threshold, **kwargs)
    241         self.pair_df = self.pair(
--> 242             buffer_size, min_tolerance, percent_tolerance, large_transition)
    243         self.centroids = hart85_means_shift_cluster(self.pair_df, cols)
    244 

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in pair(self, buffer_size, min_tolerance, percent_tolerance, large_transition)
    256                 buffer.clean_buffer()
    257             buffer.add_transition(s)
--> 258             buffer.pair_transitions()
    259         return buffer.matched_pairs
    260 

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in pair_transitions(self)
    184                                               0:self._num_measurements] + compval[0:self._num_measurements]
    185                                 self.matched_pairs.loc[
--> 186                                     len(self.matched_pairs)] = matchedpair
    187 
    188                     # Iterate Index

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\indexing.py in __setitem__(self, key, value)
    192             key = com._apply_if_callable(key, self.obj)
    193         indexer = self._get_setitem_indexer(key)
--> 194         self._setitem_with_indexer(indexer, value)
    195 
    196     def _has_valid_type(self, k, axis):

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
    443                                        name=indexer)
    444 
--> 445                     self.obj._data = self.obj.append(value)._data
    446                     self.obj._maybe_update_cacher(clear=True)
    447                     return self.obj

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py in append(self, other, ignore_index, verify_integrity)
    5192             to_concat = [self, other]
    5193         return concat(to_concat, ignore_index=ignore_index,
--> 5194                       verify_integrity=verify_integrity)
    5195 
    5196     def join(self, other, on=None, how='left', lsuffix='', rsuffix='',

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\reshape\concat.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    211                        verify_integrity=verify_integrity,
    212                        copy=copy)
--> 213     return op.get_result()
    214 
    215 

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\reshape\concat.py in get_result(self)
    406             new_data = concatenate_block_managers(
    407                 mgrs_indexers, self.new_axes, concat_axis=self.axis,
--> 408                 copy=self.copy)
    409             if not self.copy:
    410                 new_data._consolidate_inplace()

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
    5201         else:
    5202             b = make_block(
--> 5203                 concatenate_join_units(join_units, concat_axis, copy=copy),
    5204                 placement=placement)
    5205         blocks.append(b)

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py in concatenate_join_units(join_units, concat_axis, copy)
    5330     to_concat = [ju.get_reindexed_values(empty_dtype=empty_dtype,
    5331                                          upcasted_na=upcasted_na)
--> 5332                  for ju in join_units]
    5333 
    5334     if len(to_concat) == 1:

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py in <listcomp>(.0)
    5330     to_concat = [ju.get_reindexed_values(empty_dtype=empty_dtype,
    5331                                          upcasted_na=upcasted_na)
--> 5332                  for ju in join_units]
    5333 
    5334     if len(to_concat) == 1:

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py in get_reindexed_values(self, empty_dtype, upcasted_na)
    5601                     pass
    5602                 else:
--> 5603                     missing_arr = np.empty(self.shape, dtype=empty_dtype)
    5604                     missing_arr.fill(fill_value)
    5605                     return missing_arr

TypeError: data type not understood
```

I am not sure how to debug it and find out where the data type it is talking about. Maybe there is some issue with my metadata. Would you mind to investigate with me about this?

(EDIT BY @PMeira: tweak formatting)

**Comment by omegawea** [comment] 2018-06-12 06:23
https://github.com/omegawea/metadata_converter
i tried to upload my conversion code and h5 files to github (iam new to these). I wonder if you can see something.

**Comment by omegawea** [comment] 2018-06-12 12:22
i tried to replace my Anaconda3 pandas to nilmtk pandas. 
```
hart = hart_85.Hart85()
hart.train(top_3_train_elec)
```
Then TypeError disappeared.
```
Loading data for meter ElecMeterID(instance=2, building=1, dataset='ALD')     
G:\Downloads\Program\nilmtk\nilmtk\metergroup.py:1768: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  cumulator_arr = cumulator.as_matrix()
Loading data for meter ElecMeterID(instance=5, building=1, dataset='ALD')      
Done loading data all meters for this chunk.
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
```
but seem the model is not trained even it said finished:
```
output = HDFDataStore('disagre.h5', 'w')
hart.disaggregate(test_elec.mains(), output, sample_period=chooseSample)
output.close()
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-80795cf90c26> in <module>()
      1 output = HDFDataStore('disagre.h5', 'w')
----> 2 hart.disaggregate(test_elec.mains(), output, sample_period=chooseSample)
      3 output.close()

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    388             Passed to `mains.power_series(**kwargs)`
    389         """
--> 390         load_kwargs = self._pre_disaggregation_checks(load_kwargs)
    391 
    392         load_kwargs.setdefault('sample_period', 60)

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\disaggregator.py in _pre_disaggregation_checks(self, load_kwargs)
     83         if not self.model:
     84             raise RuntimeError(
---> 85                 "The model needs to be instantiated before"
     86                 " calling `disaggregate`.  For example, the"
     87                 " model can be instantiated by running `train`.")

RuntimeError: The model needs to be instantiated before calling `disaggregate`.  For example, the model can be instantiated by running `train`.
```

**Comment by omegawea** [comment] 2018-06-14 03:54
any chance if someone can help on this?

**Comment by omegawea** [comment] 2018-06-15 04:43
a bit more observation found in hart_85.py
at the beginning of def disaggregate(self, mains, output_datastore, **load_kwargs):
i think it checks if the model is trained or not:
`load_kwargs = self._pre_disaggregation_checks(load_kwargs)`

However, i cannot find _pre_disaggregation_checks in class Hart85(Disaggregator)
Also, _save_metadata_for_disaggregation is not existed in the class.

i am not an expert in python, maybe these 2 def are called from elsewhere not in the class, im not sure.
Anyways, i found a hart_85 code in [here](http://nilmtk.github.io/nilmtk/master/_modules/nilmtk/disaggregate/hart_85.html).
hart.disaggregate(test_elec.mains()) works with this code (although i have to modify the import library a bit)

yet the disaggregation was working on active power only dataset, not working with active and reactive power dataset. I think it would be hard to go further by myself.

Hope to hear back from you guyz soon.

**Comment by nipunbatra** [comment] 2018-06-15 05:29
What documentation did you refer for this code? I think we didn't update the documentation for Hart's method!

**Comment by omegawea** [comment] 2018-06-15 05:56
thanks for the reply.
i found the hart_85.py in nilmtk\nilmtk\disaggregate folder and had a look.
i understand the document in [here](http://nilmtk.github.io/nilmtk/master/_modules/nilmtk/disaggregate/hart_85.html) is not up-to-date.
yet it is available so i gave a try to see if the previous code is working or not.

**Comment by PMeira** [comment] 2018-06-26 23:09
@omegawea I fixed a couple of things related to this recently, it may run now.

**Comment by omegawea** [comment] 2018-07-09 12:39
Thanks for the update. seem to me when it comes to active and reactive power dataset. it has error.

```
start = time.time()
hart = hart_85.Hart85()
hart.train(train_elec, sample_period=1, cols=[('power', 'active'), ('power', 'reactive')])
end = time.time()
print("Runtime =", end-start, "seconds.")

Loading data for meter ElecMeterID(instance=13, building=1, dataset='ALD')     
Done loading data all meters for this chunk.
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
Runtime = 17.04450035095215 seconds.

disag_filename = 'harttest.h5'
output = HDFDataStore(disag_filename, 'w')
hart.disaggregate(test_elec.mains(), output, sample_period=1)
output.close()

Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-153-87ebb7c970a8> in <module>()
      1 disag_filename = 'harttest.h5'
      2 output = HDFDataStore(disag_filename, 'w')
----> 3 hart.disaggregate(test_elec.mains(), output, sample_period=1)
      4 output.close()

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    432             measurement = chunk.name
    433             power_df = self.disaggregate_chunk(
--> 434                 chunk, prev, transients)
    435 
    436             cols = pd.MultiIndex.from_tuples([chunk.name])

G:\Downloads\Program\nilmtk\nilmtk\disaggregate\hart_85.py in disaggregate_chunk(self, chunk, prev, transients)
    325         prev = states.iloc[-1].to_dict()
    326         power_chunk_dict = self.assign_power_from_states(states, prev)
--> 327         return pd.DataFrame(power_chunk_dict, index=chunk.index)
    328 
    329     def assign_power_from_states(self, states_chunk, prev):

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    346                                  dtype=dtype, copy=copy)
    347         elif isinstance(data, dict):
--> 348             mgr = self._init_dict(data, index, columns, dtype=dtype)
    349         elif isinstance(data, ma.MaskedArray):
    350             import numpy.ma.mrecords as mrecords

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py in _init_dict(self, data, index, columns, dtype)
    457             arrays = [data[k] for k in keys]
    458 
--> 459         return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    460 
    461     def _init_ndarray(self, values, index, columns, dtype=None, copy=False):

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   7316 
   7317     # don't force copy because getting jammed in an ndarray anyway
-> 7318     arrays = _homogenize(arrays, index, dtype)
   7319 
   7320     # from BlockManager perspective

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py in _homogenize(data, index, dtype)
   7626                 v = lib.fast_multiget(v, oindex.values, default=np.nan)
   7627             v = _sanitize_array(v, index, dtype=dtype, copy=False,
-> 7628                                 raise_cast_failure=False)
   7629 
   7630         homogenized.append(v)

D:\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\series.py in _sanitize_array(data, index, dtype, copy, raise_cast_failure)
   4159     elif subarr.ndim > 1:
   4160         if isinstance(data, np.ndarray):
-> 4161             raise Exception('Data must be 1-dimensional')
   4162         else:
   4163             subarr = com._asarray_tuplesafe(data, dtype=dtype)

Exception: Data must be 1-dimensional
```
Or does it mean no longer support active reactive power dataset?

**Comment by PMeira** [comment] 2018-07-10 17:53
@omegawea Thanks for reporting back. 

> Or does it mean no longer support active reactive power dataset?

I'll try to reproduce the issue with other datasets tomorrow. The Hart85 code has limitations and needs some work but it could be it's just something caused by the API changes in Pandas we didn't track.

**Comment by omegawea** [comment] 2018-07-12 07:49
Hi, thanks for the prompt responses.
I wonder how far you are and may be you can make use of my metadata and result to see if anything fishy on my side.
I tried to upload my stuff to github.
[](https://github.com/omegawea/metadata_converter)
Please check the Hart_85_issue.ipynb result and metadata fqpsenergy.h5

**Comment by PMeira** [comment] 2018-07-17 11:46
@omegawea Sorry, ran out of time last week. I'll give priority to this issue as soon as I finish some other tasks. Thank you for providing an easy way to reproduce it!

**Comment by omegawea** [comment] 2018-07-17 14:44
@PMeira thanks for the reply as well. 
unfortunately, my project will be due in two weeks 
I would live with the results I got anyways so take it easy.
if any other help I can offer, please do tell me.

**Comment by SebML** [comment] 2018-10-18 10:21
@PMeira I am getting the same error " Exception: Data must be 1-dimensional " as omegawea. It would be nice to have Hart algo working with both active and reactive trained data...

**Comment by rajatgupta1234** [comment] 2019-06-15 05:00
@omegawea @PMeira @5mdd 
The error of multi-index columns has been solved.  The train and disaggregate functions now work fine with both powers (active and reactive). Moreover, a documentation related to Hart85 algorithm would be added shortly. 
The code has been updated using #794.

**Comment by PMeira** [comment] 2019-06-23 19:53
Confirmed working by running with @omegawea's sample.
Thank you @rajatgupta1234, closing the issue.

**Closed by PMeira** 2019-06-23 19:53 UTC
Labels: bug

**Comment by Judy0718** [comment] 2020-06-06 08:04
> a bit more observation found in hart_85.py
> at the beginning of def disaggregate(self, mains, output_datastore, **load_kwargs):
> i think it checks if the model is trained or not:
> `load_kwargs = self._pre_disaggregation_checks(load_kwargs)`
> 
> However, i cannot find _pre_disaggregation_checks in class Hart85(Disaggregator)
> Also, _save_metadata_for_disaggregation is not existed in the class.
> 
> i am not an expert in python, maybe these 2 def are called from elsewhere not in the class, im not sure.
> Anyways, i found a hart_85 code in [here](http://nilmtk.github.io/nilmtk/master/_modules/nilmtk/disaggregate/hart_85.html).
> hart.disaggregate(test_elec.mains()) works with this code (although i have to modify the import library a bit)
> 
> yet the disaggregation was working on active power only dataset, not working with active and reactive power dataset. I think it would be hard to go further by myself.
> 
> Hope to hear back from you guyz soon.
I can't find  _pre_disaggregation_checks and  _save_metadata_for_disaggregation too. Have you solved it yet???Please
