### ISSUE TITLE
Problems with sample_period>30min in disaggregation

### ISSUE THREAD

**Issue by AndresAriasSilva** [nilmtk/nilmtk#877] opened 2020-06-26 21:49 UTC
I have been working with the REDD dataset and with a dataset created by me (with a sample_period=1s in all meters). In both cases, when I try to disaggregate (CO and FHMM) the mains with a sample_period greater than 30 minutes, no process is performed, and the output.h5 file is empty.

This function I am using without problems for periods less than 30 minutes:
`disaggregate(test_elec.mains(), output, sample_period=3600)`

Does anyone know why this happens?

Thanks

**Comment by PMeira** [comment] 2020-08-20 01:58
(Sorry for the late reply.) 
I never even considered running any detection method with that resolution resolution. Even 10 years ago it was already becoming common to use 1-second resolution.

Is there any particular reason to target >30 minutes? I'm sure you'd be able to detect something depending on the method, but a lot of events happen in 30 minutes.

**Comment by AndresAriasSilva** [comment] 2020-08-20 13:19
Thanks for your answer Pablo, it's not too late

I'm working with my own dataset (1s) and I'm evaluating the behavior of the change of sample_period in the disaggregation, for that reason I considered 30 minutes at first.

Now I'm working with a maximum of 10 minutes, but I would like to know if there is any limitation (or reason) for CO and FHMM in NILMTK code that do not allow disaggregation with long periods. Even for >15min the process is not performed well because the predictions have missing values.

**Comment by jpchavat** [comment] 2020-08-20 13:27
Hi Andres and Pablo, just for the records, I'm studying the degradation of the disaggregation methods at long sample periods. Thus, in my case, I too will be using the built-in methods with long sample periods such as 5, 15, 30 minutes.

**Comment by PMeira** [comment] 2020-08-20 13:38
Mathematically, I don't see any inherit limitation for the methods. I don't recall anything else related to the sample period or resampling that limits the upper range of the sample period, but it's a possibility. 

I'll try to check this on the weekend. Should be easy to check. If you want to give it a go, try stepping through the code with a debugger.

**Comment by PMeira** [comment] 2020-08-20 13:40
@AndresAriasSilva Did you check if the methods on [NILMTK-contrib](https://github.com/nilmtk/nilmtk-contrib/) have the same issue? That might give a clue if the issue is in the pre-processing pipeline or later.

**Comment by AndresAriasSilva** [comment] 2020-08-20 13:53
> @AndresAriasSilva Did you check if the methods on [NILMTK-contrib](https://github.com/nilmtk/nilmtk-contrib/) have the same issue? That might give a clue if the issue is in the pre-processing pipeline or later.

I would have to check it out, but I'm not using NILMTK-API in my research work at the moment. I'll follow your advice with the debugger for FHMM and CO code. Thanks!

**Comment by PMeira** [comment] 2020-08-24 00:52
I believe the main issue is the check for the minimum number of samples (defaults to 100). Try something like

```python
#...
clf = CombinatorialOptimisation()
clf.MIN_CHUNK_LENGTH = 1
sample_period = 3600
clf.train(top_5_train_elec, sample_period=sample_period)
clf.disaggregate(test_elec.mains(), output, sample_period=sample_period)
```

There could be warnings about number of clusters (with such a low sample rate, sometimes there is only one, that is, no events for some appliances), otherwise it seems to work fine. Using `.disaggregate_chunk()` and iterating the chunks much like in the old example notebooks also seems to work as expected.

**Comment by AndresAriasSilva** [comment] 2020-08-24 14:18
Thanks @PMeira! It has worked well for me too.

At first I thought there might be a limitation to the number of samples, but I didn't find anything in the code. Could you tell me in which part of the code the limitation of 100 samples is made? Sorry for asking too much, I'm getting started on this

Thanks again

**Comment by PMeira** [comment] 2020-08-25 00:59
Great, I'm closing this then. Of course, feel free to reopen if similar issues pop up somewhere else.

> At first I thought there might be a limitation to the number of samples, but I didn't find anything in the code. Could you tell me in which part of the code the limitation of 100 samples is made

@AndresAriasSilva It's that `MIN_CHUNK_LENGTH` attribute, which is populated in the legacy classes for CO and FHMM:

https://github.com/nilmtk/nilmtk/blob/4e38fd5fbf43b43d82c81deeb11fa4a5564e1ac9/nilmtk/legacy/disaggregate/combinatorial_optimisation.py#L41

https://github.com/nilmtk/nilmtk/blob/ffcf3d105410e39ec7d6dd72dfd269e11006ace3/nilmtk/legacy/disaggregate/fhmm_exact.py#L209

**Closed by PMeira** 2020-08-25 00:59 UTC
